// Existing backend authorities; the server remains the access boundary.
export const FUNCTION_PERMISSIONS = [
  'FUNCTIONS_VIEW', 'FUNCTIONS_CREATE', 'FUNCTIONS_EDIT', 'FUNCTIONS_MANAGE_REQUIREMENTS',
  'FUNCTIONS_DEACTIVATE', 'FUNCTIONS_SUBMIT_REVIEW', 'FUNCTIONS_REVIEW',
  'FUNCTIONS_PUBLISH', 'FUNCTIONS_REACTIVATE', 'FUNCTIONS_TRANSLATIONS_EDIT',
  'FUNCTION_CATEGORIES_MANAGE', 'FUNCTIONS_IMPORT', 'AUDIT_VIEW',
] as const;
