package adliya.uz.functioncatalogservice.entity;

public enum AuditAction {
    CREATE, UPDATE, DELETE, SUBMIT_REVIEW, REJECT, PUBLISH, DEACTIVATE, REACTIVATE,
    CATEGORY_CHANGE, TRANSLATION_EDIT, IMPORT, VERIFY, REPORT_RECEIVED, REPORT_STATUS_CHANGE
}
