-- Preserve legacy cards, including their publication state and category names.
CREATE TABLE IF NOT EXISTS org_functions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    name_translations JSONB,
    description_translations JSONB,
    organization_id BIGINT NOT NULL,
    requirements VARCHAR(500),
    category VARCHAR(100),
    active BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE function_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    name_translations JSONB,
    version BIGINT NOT NULL DEFAULT 0
);
ALTER TABLE org_functions ADD COLUMN status VARCHAR(30);
UPDATE org_functions SET status = CASE WHEN active THEN 'PUBLISHED' ELSE 'DEACTIVATED' END;
ALTER TABLE org_functions ALTER COLUMN status SET NOT NULL;
ALTER TABLE org_functions ALTER COLUMN status SET DEFAULT 'DRAFT';
ALTER TABLE org_functions ADD CONSTRAINT org_functions_status_check
    CHECK (status IN ('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'DEACTIVATED'));
ALTER TABLE org_functions ALTER COLUMN organization_id DROP NOT NULL;
ALTER TABLE org_functions ADD CONSTRAINT org_functions_review_organization_check
    CHECK (status NOT IN ('PENDING_REVIEW', 'PUBLISHED') OR organization_id IS NOT NULL);
ALTER TABLE org_functions ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE org_functions ADD COLUMN seed_key VARCHAR(100) UNIQUE;
ALTER TABLE org_functions ADD COLUMN category_id BIGINT REFERENCES function_categories(id);
INSERT INTO function_categories(name, name_translations)
    SELECT DISTINCT category, '{}'::jsonb FROM org_functions WHERE category IS NOT NULL AND btrim(category) <> '';
UPDATE org_functions f SET category_id = c.id FROM function_categories c WHERE f.category = c.name;
ALTER TABLE org_functions DROP COLUMN active;
ALTER TABLE org_functions DROP COLUMN category;
CREATE INDEX org_functions_status_org_idx ON org_functions(status, organization_id);
CREATE INDEX org_functions_category_idx ON org_functions(category_id);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT,
    action VARCHAR(40) NOT NULL,
    performed_by_user_id BIGINT,
    performed_by VARCHAR(320) NOT NULL,
    performed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    details TEXT
);
CREATE TABLE audit_log_functions (
    audit_log_id BIGINT NOT NULL REFERENCES audit_logs(id),
    function_id BIGINT NOT NULL REFERENCES org_functions(id),
    PRIMARY KEY(audit_log_id, function_id)
);
CREATE INDEX audit_log_functions_function_idx ON audit_log_functions(function_id);
