ALTER TABLE org_functions ADD COLUMN IF NOT EXISTS who_can_use VARCHAR(2000);
ALTER TABLE org_functions ADD COLUMN IF NOT EXISTS steps VARCHAR(4000);
ALTER TABLE org_functions ADD COLUMN IF NOT EXISTS required_documents VARCHAR(4000);
ALTER TABLE org_functions ADD COLUMN IF NOT EXISTS where_how_to_apply VARCHAR(2000);
ALTER TABLE org_functions ADD COLUMN IF NOT EXISTS processing_time VARCHAR(500);
ALTER TABLE org_functions ADD COLUMN IF NOT EXISTS fee VARCHAR(500);
ALTER TABLE org_functions ADD COLUMN IF NOT EXISTS official_source_url VARCHAR(500);
ALTER TABLE org_functions ADD COLUMN IF NOT EXISTS instruction_translations JSONB;
ALTER TABLE org_functions ADD COLUMN IF NOT EXISTS last_verified_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE org_functions ADD COLUMN IF NOT EXISTS verified_by_user_id BIGINT;
ALTER TABLE org_functions ADD COLUMN IF NOT EXISTS verification_outdated BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS information_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(20) NOT NULL,
    entity_id BIGINT NOT NULL,
    entity_label VARCHAR(150) NOT NULL,
    organization_id BIGINT NOT NULL,
    category VARCHAR(40) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    contact VARCHAR(254),
    language VARCHAR(35),
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    resolution_note VARCHAR(2000),
    handled_by_user_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT information_reports_entity_type_check CHECK (entity_type IN ('FUNCTION', 'ORGANIZATION')),
    CONSTRAINT information_reports_status_check CHECK (status IN ('NEW', 'IN_REVIEW', 'RESOLVED', 'DISMISSED'))
);
CREATE INDEX IF NOT EXISTS information_reports_scope_idx ON information_reports(organization_id, status, created_at);
CREATE INDEX IF NOT EXISTS information_reports_entity_idx ON information_reports(entity_type, entity_id, created_at);
