CREATE TABLE IF NOT EXISTS engagement_daily_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_date DATE NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    organization_id BIGINT,
    function_id BIGINT REFERENCES org_functions(id),
    event_count BIGINT NOT NULL,
    CONSTRAINT engagement_daily_counts_event_type_check CHECK (event_type IN
        ('CATALOG_VIEW', 'SERVICE_VIEW', 'OFFICIAL_LINK_CLICK', 'PHONE_CLICK', 'MAP_CLICK', 'PRINT')),
    CONSTRAINT engagement_daily_counts_count_check CHECK (event_count > 0),
    CONSTRAINT engagement_daily_counts_key UNIQUE NULLS NOT DISTINCT (activity_date, event_type, organization_id, function_id)
);
CREATE INDEX IF NOT EXISTS engagement_daily_counts_scope_idx ON engagement_daily_counts(organization_id, activity_date);
CREATE INDEX IF NOT EXISTS engagement_daily_counts_function_idx ON engagement_daily_counts(function_id, activity_date);
