CREATE TABLE IF NOT EXISTS quality_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    function_id BIGINT NOT NULL REFERENCES org_functions(id),
    organization_id BIGINT NOT NULL,
    issue VARCHAR(40) NOT NULL,
    detected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    notified_at TIMESTAMP WITH TIME ZONE NOT NULL,
    acknowledged_at TIMESTAMP WITH TIME ZONE,
    acknowledged_by_user_id BIGINT,
    resolved_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT quality_reminders_issue_check CHECK (issue IN
        ('VERIFICATION_OVERDUE', 'SOURCE_MISSING', 'INFORMATION_INCOMPLETE', 'TRANSLATIONS_MISSING'))
);
CREATE UNIQUE INDEX IF NOT EXISTS quality_reminders_open_issue_idx ON quality_reminders(function_id, issue) WHERE resolved_at IS NULL;
CREATE INDEX IF NOT EXISTS quality_reminders_scope_idx ON quality_reminders(organization_id, resolved_at);
