-- Labels use the existing reference-service translation store.
CREATE TEMPORARY TABLE admin_function_labels (key VARCHAR(150), lang VARCHAR(64), value TEXT) ON COMMIT DROP;
INSERT INTO admin_function_labels VALUES
('fnAdmin.subtitle', 'en', 'Drafts, review queue and published services.'),
('fnAdmin.subtitle', 'ru', 'Черновики, очередь проверки и опубликованные услуги.'),
('fnAdmin.subtitle', 'uz', 'Qoralamalar, tekshiruv navbati va e’lon qilingan xizmatlar.'),
('fnAdmin.subtitle', 'fr', 'Brouillons, révision et services publiés.'),
('fnAdmin.status.DRAFT', 'en', 'Draft'),
('fnAdmin.status.DRAFT', 'ru', 'Черновик'),
('fnAdmin.status.DRAFT', 'uz', 'Qoralama'),
('fnAdmin.status.DRAFT', 'fr', 'Brouillon'),
('fnAdmin.status.PENDING_REVIEW', 'en', 'Pending review'),
('fnAdmin.status.PENDING_REVIEW', 'ru', 'На проверке'),
('fnAdmin.status.PENDING_REVIEW', 'uz', 'Tekshiruvda'),
('fnAdmin.status.PENDING_REVIEW', 'fr', 'En révision'),
('fnAdmin.status.PUBLISHED', 'en', 'Published'),
('fnAdmin.status.PUBLISHED', 'ru', 'Опубликовано'),
('fnAdmin.status.PUBLISHED', 'uz', 'E’lon qilingan'),
('fnAdmin.status.PUBLISHED', 'fr', 'Publié'),
('fnAdmin.status.DEACTIVATED', 'en', 'Deactivated'),
('fnAdmin.status.DEACTIVATED', 'ru', 'Деактивировано'),
('fnAdmin.status.DEACTIVATED', 'uz', 'Faolsizlantirilgan'),
('fnAdmin.status.DEACTIVATED', 'fr', 'Désactivé'),
('fnAdmin.unassigned', 'en', 'Unassigned'),
('fnAdmin.unassigned', 'ru', 'Без организации'),
('fnAdmin.unassigned', 'uz', 'Tashkilot tanlanmagan'),
('fnAdmin.unassigned', 'fr', 'Sans organisation'),
('fnAdmin.missingTranslation', 'en', 'Translation missing; showing original'),
('fnAdmin.missingTranslation', 'ru', 'Перевод отсутствует; показан оригинал'),
('fnAdmin.missingTranslation', 'uz', 'Tarjima yo‘q; asl matn ko‘rsatilgan'),
('fnAdmin.missingTranslation', 'fr', 'Traduction absente ; texte original'),
('fnAdmin.languages', 'en', 'Languages'),
('fnAdmin.languages', 'ru', 'Языки'),
('fnAdmin.languages', 'uz', 'Tillar'),
('fnAdmin.languages', 'fr', 'Langues'),
('fnAdmin.previous', 'en', 'Previous'),
('fnAdmin.previous', 'ru', 'Назад'),
('fnAdmin.previous', 'uz', 'Oldingi'),
('fnAdmin.previous', 'fr', 'Précédent'),
('fnAdmin.next', 'en', 'Next'),
('fnAdmin.next', 'ru', 'Далее'),
('fnAdmin.next', 'uz', 'Keyingi'),
('fnAdmin.next', 'fr', 'Suivant'),
('fnAdmin.create', 'en', 'Create service'),
('fnAdmin.create', 'ru', 'Создать услугу'),
('fnAdmin.create', 'uz', 'Xizmat yaratish'),
('fnAdmin.create', 'fr', 'Créer un service'),
('fnAdmin.sourceLanguage', 'en', 'Original language'),
('fnAdmin.sourceLanguage', 'ru', 'Исходный язык'),
('fnAdmin.sourceLanguage', 'uz', 'Asl matn tili'),
('fnAdmin.sourceLanguage', 'fr', 'Langue originale'),
('fnAdmin.choose', 'en', 'Select…'),
('fnAdmin.choose', 'ru', 'Выберите…'),
('fnAdmin.choose', 'uz', 'Tanlang…'),
('fnAdmin.choose', 'fr', 'Sélectionner…'),
('fnAdmin.noCategory', 'en', 'No category'),
('fnAdmin.noCategory', 'ru', 'Без категории'),
('fnAdmin.noCategory', 'uz', 'Toifasiz'),
('fnAdmin.noCategory', 'fr', 'Sans catégorie'),
('fnAdmin.original', 'en', 'Original text'),
('fnAdmin.original', 'ru', 'Исходный текст'),
('fnAdmin.original', 'uz', 'Asl matn'),
('fnAdmin.original', 'fr', 'Texte original'),
('fnAdmin.originalHint', 'en', 'Edit the original here; use Translations for other languages.'),
('fnAdmin.originalHint', 'ru', 'Здесь редактируется оригинал; другие языки — в разделе «Переводы».'),
('fnAdmin.originalHint', 'uz', 'Bu yerda asl matn tahrirlanadi; boshqa tillar «Tarjimalar» bo‘limida.'),
('fnAdmin.originalHint', 'fr', 'Modifiez l’original ici ; les autres langues sont dans Traductions.'),
('fnAdmin.unsaved', 'en', 'Unsaved changes'),
('fnAdmin.unsaved', 'ru', 'Есть несохранённые изменения'),
('fnAdmin.unsaved', 'uz', 'Saqlanmagan o‘zgarishlar bor'),
('fnAdmin.unsaved', 'fr', 'Modifications non enregistrées'),
('fnAdmin.discard', 'en', 'Leave without saving changes?'),
('fnAdmin.discard', 'ru', 'Выйти без сохранения изменений?'),
('fnAdmin.discard', 'uz', 'O‘zgarishlarni saqlamasdan chiqilsinmi?'),
('fnAdmin.discard', 'fr', 'Quitter sans enregistrer ?'),
('fnAdmin.saved', 'en', 'Changes saved'),
('fnAdmin.saved', 'ru', 'Изменения сохранены'),
('fnAdmin.saved', 'uz', 'O‘zgarishlar saqlandi'),
('fnAdmin.saved', 'fr', 'Modifications enregistrées'),
('fnAdmin.readOnly', 'en', 'This card is read-only in its current status.'),
('fnAdmin.readOnly', 'ru', 'При текущем статусе карточка доступна только для чтения.'),
('fnAdmin.readOnly', 'uz', 'Joriy holatda kartochkani faqat o‘qish mumkin.'),
('fnAdmin.readOnly', 'fr', 'Cette fiche est en lecture seule dans son état actuel.'),
('fnAdmin.reviewHint', 'en', 'Under review. A reviewer can return the card to draft.'),
('fnAdmin.reviewHint', 'ru', 'На проверке. Рецензент может вернуть карточку на доработку.'),
('fnAdmin.reviewHint', 'uz', 'Tekshiruvda. Tekshiruvchi kartochkani qoralamaga qaytarishi mumkin.'),
('fnAdmin.reviewHint', 'fr', 'En révision. Le réviseur peut renvoyer la fiche en brouillon.'),
('fnAdmin.publishedHint', 'en', 'To edit: deactivate, return to review, then have a reviewer return it to draft.'),
('fnAdmin.publishedHint', 'ru', 'Для правок: деактивируйте, верните на проверку, затем рецензент вернёт карточку в черновик.'),
('fnAdmin.publishedHint', 'uz', 'Tahrirlash uchun faolsizlantiring, tekshiruvga qaytaring, keyin tekshiruvchi qoralamaga qaytaradi.'),
('fnAdmin.publishedHint', 'fr', 'Pour modifier : désactivez, renvoyez en révision, puis demandez le retour en brouillon.'),
('fnAdmin.deactivatedHint', 'en', 'Return to review; a reviewer can then return this card to draft.'),
('fnAdmin.deactivatedHint', 'ru', 'Верните на проверку; рецензент сможет вернуть карточку в черновик.'),
('fnAdmin.deactivatedHint', 'uz', 'Tekshiruvga qaytaring; tekshiruvchi kartochkani qoralamaga qaytarishi mumkin.'),
('fnAdmin.deactivatedHint', 'fr', 'Renvoyez en révision ; le réviseur pourra renvoyer la fiche en brouillon.'),
('fnAdmin.submit', 'en', 'Submit for review'),
('fnAdmin.submit', 'ru', 'Отправить на проверку'),
('fnAdmin.submit', 'uz', 'Tekshiruvga yuborish'),
('fnAdmin.submit', 'fr', 'Soumettre à révision'),
('fnAdmin.publish', 'en', 'Publish'),
('fnAdmin.publish', 'ru', 'Опубликовать'),
('fnAdmin.publish', 'uz', 'E’lon qilish'),
('fnAdmin.publish', 'fr', 'Publier'),
('fnAdmin.reject', 'en', 'Return to draft'),
('fnAdmin.reject', 'ru', 'Вернуть на доработку'),
('fnAdmin.reject', 'uz', 'Qoralamaga qaytarish'),
('fnAdmin.reject', 'fr', 'Renvoyer en brouillon'),
('fnAdmin.reason', 'en', 'Reason for returning'),
('fnAdmin.reason', 'ru', 'Причина возврата'),
('fnAdmin.reason', 'uz', 'Qaytarish sababi'),
('fnAdmin.reason', 'fr', 'Motif du retour'),
('fnAdmin.reactivate', 'en', 'Return to review'),
('fnAdmin.reactivate', 'ru', 'Вернуть на проверку'),
('fnAdmin.reactivate', 'uz', 'Tekshiruvga qaytarish'),
('fnAdmin.reactivate', 'fr', 'Renvoyer en révision'),
('fnAdmin.audit', 'en', 'History'),
('fnAdmin.audit', 'ru', 'История'),
('fnAdmin.audit', 'uz', 'Tarix'),
('fnAdmin.audit', 'fr', 'Historique'),
('fnAdmin.actor', 'en', 'Performed by'),
('fnAdmin.actor', 'ru', 'Кто выполнил'),
('fnAdmin.actor', 'uz', 'Bajargan'),
('fnAdmin.actor', 'fr', 'Auteur'),
('fnAdmin.assignFirst', 'en', 'Select and save an organization before submitting for review.'),
('fnAdmin.assignFirst', 'ru', 'Выберите и сохраните организацию перед отправкой на проверку.'),
('fnAdmin.assignFirst', 'uz', 'Tekshiruvga yuborishdan oldin tashkilotni tanlang va saqlang.'),
('fnAdmin.assignFirst', 'fr', 'Sélectionnez et enregistrez une organisation avant la révision.'),
('fnAdmin.saveFirst', 'en', 'Save changes before running workflow actions.'),
('fnAdmin.saveFirst', 'ru', 'Сохраните изменения перед сменой статуса.'),
('fnAdmin.saveFirst', 'uz', 'Holatni o‘zgartirishdan oldin o‘zgarishlarni saqlang.'),
('fnAdmin.saveFirst', 'fr', 'Enregistrez les modifications avant de changer le statut.'),
('fnAdmin.deactivateConfirm', 'en', 'Deactivate this service? It will disappear from the public catalogue.'),
('fnAdmin.deactivateConfirm', 'ru', 'Деактивировать услугу? Она исчезнет из публичного каталога.'),
('fnAdmin.deactivateConfirm', 'uz', 'Xizmat faolsizlantirilsinmi? U ommaviy katalogdan yo‘qoladi.'),
('fnAdmin.deactivateConfirm', 'fr', 'Désactiver ce service ? Il disparaîtra du catalogue public.'),
('fnAdmin.translations', 'en', 'Translations'),
('fnAdmin.translations', 'ru', 'Переводы'),
('fnAdmin.translations', 'uz', 'Tarjimalar'),
('fnAdmin.translations', 'fr', 'Traductions'),
('fnAdmin.human', 'en', 'Manual'),
('fnAdmin.human', 'ru', 'Ручной'),
('fnAdmin.human', 'uz', 'Qo‘lda'),
('fnAdmin.human', 'fr', 'Manuel'),
('fnAdmin.machine', 'en', 'Machine'),
('fnAdmin.machine', 'ru', 'Машинный'),
('fnAdmin.machine', 'uz', 'Avtomatik'),
('fnAdmin.machine', 'fr', 'Automatique'),
('fnAdmin.originalLanguageHint', 'en', 'Edit this language in Original text.'),
('fnAdmin.originalLanguageHint', 'ru', 'Этот язык редактируется в исходном тексте.'),
('fnAdmin.originalLanguageHint', 'uz', 'Bu tilni «Asl matn» bo‘limida tahrirlang.'),
('fnAdmin.originalLanguageHint', 'fr', 'Modifiez cette langue dans Texte original.'),
('fnAdmin.requirementsHint', 'en', 'Requirements are stored only in the original language.'),
('fnAdmin.requirementsHint', 'ru', 'Требования хранятся только на исходном языке.'),
('fnAdmin.requirementsHint', 'uz', 'Talablar faqat asl tilda saqlanadi.'),
('fnAdmin.requirementsHint', 'fr', 'Les conditions sont conservées dans la langue originale.'),
('fnAdmin.translate', 'en', 'Translate missing languages'),
('fnAdmin.translate', 'ru', 'Перевести на недостающие языки'),
('fnAdmin.translate', 'uz', 'Yetishmayotgan tillarga tarjima qilish'),
('fnAdmin.translate', 'fr', 'Traduire les langues manquantes'),
('fnAdmin.regenerate', 'en', 'Regenerate machine translation'),
('fnAdmin.regenerate', 'ru', 'Обновить машинный перевод'),
('fnAdmin.regenerate', 'uz', 'Avtomatik tarjimani yangilash'),
('fnAdmin.regenerate', 'fr', 'Régénérer la traduction automatique'),
('fnAdmin.autoUnavailable', 'en', 'Automatic translation is unavailable. You can enter translations manually.'),
('fnAdmin.autoUnavailable', 'ru', 'Автоперевод недоступен. Переводы можно заполнить вручную.'),
('fnAdmin.autoUnavailable', 'uz', 'Avtomatik tarjima mavjud emas. Tarjimalarni qo‘lda kiriting.'),
('fnAdmin.autoUnavailable', 'fr', 'La traduction automatique est indisponible. Saisissez les traductions manuellement.'),
('fnAdmin.translationGaps', 'en', 'Some translations are missing.'),
('fnAdmin.translationGaps', 'ru', 'Некоторые переводы отсутствуют.'),
('fnAdmin.translationGaps', 'uz', 'Ayrim tarjimalar yetishmayapti.'),
('fnAdmin.translationGaps', 'fr', 'Certaines traductions sont manquantes.'),
('fnAdmin.retryLater', 'en', 'Retry later'),
('fnAdmin.retryLater', 'ru', 'Повторить позже'),
('fnAdmin.retryLater', 'uz', 'Keyinroq takrorlash'),
('fnAdmin.retryLater', 'fr', 'Réessayer plus tard'),
('fnAdmin.preview', 'en', 'Preview'),
('fnAdmin.preview', 'ru', 'Предпросмотр'),
('fnAdmin.preview', 'uz', 'Ko‘rib chiqish'),
('fnAdmin.preview', 'fr', 'Aperçu'),
('fnAdmin.sourceChanged', 'en', 'Changing the original text clears machine translations. Review manual translations too.'),
('fnAdmin.sourceChanged', 'ru', 'Изменение оригинала сбрасывает машинные переводы. Ручные переводы тоже нужно проверить.'),
('fnAdmin.sourceChanged', 'uz', 'Asl matn o‘zgarsa, avtomatik tarjimalar o‘chiriladi. Qo‘lda kiritilgan tarjimalarni ham tekshiring.'),
('fnAdmin.sourceChanged', 'fr', 'Modifier l’original efface les traductions automatiques. Vérifiez aussi les traductions manuelles.'),
('fnAdmin.noOrganizations', 'en', 'No accessible organizations. An administrator must assign an organization first.'),
('fnAdmin.noOrganizations', 'ru', 'Нет доступных организаций. Администратор должен сначала назначить организацию.'),
('fnAdmin.noOrganizations', 'uz', 'Ruxsat etilgan tashkilotlar yo‘q. Administrator avval tashkilot biriktirishi kerak.'),
('fnAdmin.noOrganizations', 'fr', 'Aucune organisation accessible. Un administrateur doit d’abord en attribuer une.'),
('fnAdmin.createSuccess', 'en', 'Draft created'),
('fnAdmin.createSuccess', 'ru', 'Черновик создан'),
('fnAdmin.createSuccess', 'uz', 'Qoralama yaratildi'),
('fnAdmin.createSuccess', 'fr', 'Brouillon créé'),
('fnAdmin.translationSuccess', 'en', 'Translations saved'),
('fnAdmin.translationSuccess', 'ru', 'Переводы сохранены'),
('fnAdmin.translationSuccess', 'uz', 'Tarjimalar saqlandi'),
('fnAdmin.translationSuccess', 'fr', 'Traductions enregistrées'),
('fnAdmin.refresh', 'en', 'Refresh'),
('fnAdmin.refresh', 'ru', 'Обновить'),
('fnAdmin.refresh', 'uz', 'Yangilash'),
('fnAdmin.refresh', 'fr', 'Actualiser');
INSERT INTO translation_keys (translation_key, required, active)
SELECT DISTINCT key, TRUE, TRUE FROM admin_function_labels ON CONFLICT (translation_key) DO NOTHING;
INSERT INTO translations (translation_key_id, language_code, translation_value)
SELECT k.id, s.lang, s.value FROM admin_function_labels s JOIN translation_keys k ON k.translation_key = s.key
ON CONFLICT (language_code, translation_key_id) DO NOTHING;
