CREATE TEMPORARY TABLE frontend_redesign_labels (key VARCHAR(150), lang VARCHAR(64), value TEXT) ON COMMIT DROP;
INSERT INTO frontend_redesign_labels VALUES
('a11y.openMenu', 'en', 'Open menu'),
('a11y.openMenu', 'ru', 'Открыть меню'),
('a11y.openMenu', 'uz', 'Menyuni ochish'),
('a11y.openMenu', 'fr', 'Ouvrir le menu'),
('a11y.skipToContent', 'en', 'Skip to main content'),
('a11y.skipToContent', 'ru', 'Перейти к основному содержимому'),
('a11y.skipToContent', 'uz', 'Asosiy tarkibga o‘tish'),
('a11y.skipToContent', 'fr', 'Aller au contenu principal'),
('action.reactivate', 'en', 'Reactivate'),
('action.reactivate', 'ru', 'Активировать снова'),
('action.reactivate', 'uz', 'Qayta faollashtirish'),
('action.reactivate', 'fr', 'Réactiver'),
('action.select', 'en', 'Select role'),
('action.select', 'ru', 'Выберите роль'),
('action.select', 'uz', 'Rolni tanlang'),
('action.select', 'fr', 'Choisir un rôle'),
('admin.statusBreakdown', 'en', 'Catalogue status'),
('admin.statusBreakdown', 'ru', 'Состояние каталога'),
('admin.statusBreakdown', 'uz', 'Katalog holati'),
('admin.statusBreakdown', 'fr', 'État du catalogue'),
('error.badRequest', 'en', 'The submitted data is invalid'),
('error.badRequest', 'ru', 'Отправленные данные некорректны'),
('error.badRequest', 'uz', 'Yuborilgan ma’lumotlar noto‘g‘ri'),
('error.badRequest', 'fr', 'Les données envoyées sont invalides'),
('error.conflict', 'en', 'The operation conflicts with the current state'),
('error.conflict', 'ru', 'Операция конфликтует с текущим состоянием'),
('error.conflict', 'uz', 'Amal joriy holatga zid'),
('error.conflict', 'fr', 'L’opération entre en conflit avec l’état actuel'),
('error.network', 'en', 'Could not reach the server'),
('error.network', 'ru', 'Не удалось связаться с сервером'),
('error.network', 'uz', 'Serverga ulanib bo‘lmadi'),
('error.network', 'fr', 'Impossible de joindre le serveur'),
('error.notFound', 'en', 'Not found'),
('error.notFound', 'ru', 'Не найдено'),
('error.notFound', 'uz', 'Topilmadi'),
('error.notFound', 'fr', 'Introuvable'),
('error.sessionExpired', 'en', 'Your session has expired, sign in again'),
('error.sessionExpired', 'ru', 'Сессия истекла, войдите снова'),
('error.sessionExpired', 'uz', 'Sessiya muddati tugadi, qaytadan kiring'),
('error.sessionExpired', 'fr', 'Votre session a expiré, reconnectez-vous'),
('error.unexpected', 'en', 'Something went wrong'),
('error.unexpected', 'ru', 'Что-то пошло не так'),
('error.unexpected', 'uz', 'Kutilmagan xatolik yuz berdi'),
('error.unexpected', 'fr', 'Une erreur est survenue'),
('fn.organizationUnknown', 'en', 'Organization unknown'),
('fn.organizationUnknown', 'ru', 'Организация не определена'),
('fn.organizationUnknown', 'uz', 'Tashkilot aniqlanmadi'),
('fn.organizationUnknown', 'fr', 'Organisation inconnue'),
('fnAdmin.allTranslated', 'en', 'Every active language is covered.'),
('fnAdmin.allTranslated', 'ru', 'Все активные языки переведены.'),
('fnAdmin.allTranslated', 'uz', 'Barcha faol tillar uchun tarjima mavjud.'),
('fnAdmin.allTranslated', 'fr', 'Toutes les langues actives sont couvertes.'),
('fnAdmin.autoTitle', 'en', 'Automatic translation'),
('fnAdmin.autoTitle', 'ru', 'Автоматический перевод'),
('fnAdmin.autoTitle', 'uz', 'Avtomatik tarjima'),
('fnAdmin.autoTitle', 'fr', 'Traduction automatique'),
('fnAdmin.discardChanges', 'en', 'Discard'),
('fnAdmin.discardChanges', 'ru', 'Отменить изменения'),
('fnAdmin.discardChanges', 'uz', 'Bekor qilish'),
('fnAdmin.discardChanges', 'fr', 'Abandonner'),
('fnAdmin.filters', 'en', 'Filters'),
('fnAdmin.filters', 'ru', 'Фильтры'),
('fnAdmin.filters', 'uz', 'Filtrlar'),
('fnAdmin.filters', 'fr', 'Filtres'),
('fnAdmin.guide.title', 'en', 'How publishing works'),
('fnAdmin.guide.title', 'ru', 'Как происходит публикация'),
('fnAdmin.guide.title', 'uz', 'Nashr qilish qanday ishlaydi'),
('fnAdmin.guide.title', 'fr', 'Comment fonctionne la publication'),
('fnAdmin.guide.draft', 'en', 'Describe the service in its original language and assign an organization.'),
('fnAdmin.guide.draft', 'ru', 'Опишите услугу на языке оригинала и назначьте организацию.'),
('fnAdmin.guide.draft', 'uz', 'Xizmatni asl tilida tasvirlang va tashkilot biriktiring.'),
('fnAdmin.guide.draft', 'fr', 'Décrivez le service dans sa langue d’origine et attribuez une organisation.'),
('fnAdmin.guide.translate', 'en', 'Add or generate translations for every active interface language.'),
('fnAdmin.guide.translate', 'ru', 'Добавьте или сгенерируйте переводы для всех активных языков интерфейса.'),
('fnAdmin.guide.translate', 'uz', 'Barcha faol interfeys tillari uchun tarjima qo‘shing yoki yarating.'),
('fnAdmin.guide.translate', 'fr', 'Ajoutez ou générez des traductions pour chaque langue active.'),
('fnAdmin.guide.review', 'en', 'Submit the draft for review; a reviewer publishes it or returns it with a reason.'),
('fnAdmin.guide.review', 'ru', 'Отправьте черновик на проверку; проверяющий опубликует его или вернёт с указанием причины.'),
('fnAdmin.guide.review', 'uz', 'Qoralamani tekshiruvga yuboring; tekshiruvchi uni e’lon qiladi yoki sabab bilan qaytaradi.'),
('fnAdmin.guide.review', 'fr', 'Soumettez le brouillon à révision ; un relecteur le publie ou le renvoie avec un motif.'),
('fnAdmin.guide.publish', 'en', 'Published services appear in the public catalogue immediately.'),
('fnAdmin.guide.publish', 'ru', 'Опубликованные услуги сразу появляются в публичном каталоге.'),
('fnAdmin.guide.publish', 'uz', 'E’lon qilingan xizmatlar darhol ommaviy katalogda ko‘rinadi.'),
('fnAdmin.guide.publish', 'fr', 'Les services publiés apparaissent immédiatement dans le catalogue public.'),
('fnAdmin.keepEditing', 'en', 'Keep editing'),
('fnAdmin.keepEditing', 'ru', 'Продолжить редактирование'),
('fnAdmin.keepEditing', 'uz', 'Tahrirni davom ettirish'),
('fnAdmin.keepEditing', 'fr', 'Continuer la modification'),
('fnAdmin.translationsHint', 'en', 'Localized name and description for every active language.'),
('fnAdmin.translationsHint', 'ru', 'Локализованные название и описание для каждого активного языка.'),
('fnAdmin.translationsHint', 'uz', 'Har bir faol til uchun nom va tavsif tarjimasi.'),
('fnAdmin.translationsHint', 'fr', 'Nom et description localisés pour chaque langue active.'),
('fnAdmin.workflow', 'en', 'Workflow'),
('fnAdmin.workflow', 'ru', 'Рабочий процесс'),
('fnAdmin.workflow', 'uz', 'Ish jarayoni'),
('fnAdmin.workflow', 'fr', 'Flux de travail'),
('fnAdmin.action.CREATE', 'en', 'Created'),
('fnAdmin.action.CREATE', 'ru', 'Создано'),
('fnAdmin.action.CREATE', 'uz', 'Yaratildi'),
('fnAdmin.action.CREATE', 'fr', 'Créé'),
('fnAdmin.action.UPDATE', 'en', 'Updated'),
('fnAdmin.action.UPDATE', 'ru', 'Обновлено'),
('fnAdmin.action.UPDATE', 'uz', 'Yangilandi'),
('fnAdmin.action.UPDATE', 'fr', 'Mis à jour'),
('fnAdmin.action.DELETE', 'en', 'Deleted'),
('fnAdmin.action.DELETE', 'ru', 'Удалено'),
('fnAdmin.action.DELETE', 'uz', 'O‘chirildi'),
('fnAdmin.action.DELETE', 'fr', 'Supprimé'),
('fnAdmin.action.SUBMIT_REVIEW', 'en', 'Submitted for review'),
('fnAdmin.action.SUBMIT_REVIEW', 'ru', 'Отправлено на проверку'),
('fnAdmin.action.SUBMIT_REVIEW', 'uz', 'Tekshiruvga yuborildi'),
('fnAdmin.action.SUBMIT_REVIEW', 'fr', 'Soumis à révision'),
('fnAdmin.action.REJECT', 'en', 'Returned to draft'),
('fnAdmin.action.REJECT', 'ru', 'Возвращено на доработку'),
('fnAdmin.action.REJECT', 'uz', 'Qoralamaga qaytarildi'),
('fnAdmin.action.REJECT', 'fr', 'Renvoyé en brouillon'),
('fnAdmin.action.PUBLISH', 'en', 'Published'),
('fnAdmin.action.PUBLISH', 'ru', 'Опубликовано'),
('fnAdmin.action.PUBLISH', 'uz', 'E’lon qilindi'),
('fnAdmin.action.PUBLISH', 'fr', 'Publié'),
('fnAdmin.action.DEACTIVATE', 'en', 'Deactivated'),
('fnAdmin.action.DEACTIVATE', 'ru', 'Деактивировано'),
('fnAdmin.action.DEACTIVATE', 'uz', 'Faolsizlantirildi'),
('fnAdmin.action.DEACTIVATE', 'fr', 'Désactivé'),
('fnAdmin.action.REACTIVATE', 'en', 'Returned to review'),
('fnAdmin.action.REACTIVATE', 'ru', 'Возвращено на проверку'),
('fnAdmin.action.REACTIVATE', 'uz', 'Tekshiruvga qaytarildi'),
('fnAdmin.action.REACTIVATE', 'fr', 'Renvoyé en révision'),
('fnAdmin.action.CATEGORY_CHANGE', 'en', 'Category changed'),
('fnAdmin.action.CATEGORY_CHANGE', 'ru', 'Категория изменена'),
('fnAdmin.action.CATEGORY_CHANGE', 'uz', 'Kategoriya o‘zgartirildi'),
('fnAdmin.action.CATEGORY_CHANGE', 'fr', 'Catégorie modifiée'),
('fnAdmin.action.TRANSLATION_EDIT', 'en', 'Translation edited'),
('fnAdmin.action.TRANSLATION_EDIT', 'ru', 'Перевод изменён'),
('fnAdmin.action.TRANSLATION_EDIT', 'uz', 'Tarjima tahrirlandi'),
('fnAdmin.action.TRANSLATION_EDIT', 'fr', 'Traduction modifiée'),
('fnAdmin.action.IMPORT', 'en', 'Imported'),
('fnAdmin.action.IMPORT', 'ru', 'Импортировано'),
('fnAdmin.action.IMPORT', 'uz', 'Import qilindi'),
('fnAdmin.action.IMPORT', 'fr', 'Importé'),
('home.ctaImageAlt', 'en', 'Public services centre hall'),
('home.ctaImageAlt', 'ru', 'Зал центра государственных услуг'),
('home.ctaImageAlt', 'uz', 'Davlat xizmatlari markazi zali'),
('home.ctaImageAlt', 'fr', 'Hall d’un centre de services publics'),
('lang.alreadyAdded', 'en', 'Already added'),
('lang.alreadyAdded', 'ru', 'Уже добавлен'),
('lang.alreadyAdded', 'uz', 'Qo‘shilgan'),
('lang.alreadyAdded', 'fr', 'Déjà ajouté'),
('lang.nativeName', 'en', 'Native name'),
('lang.nativeName', 'ru', 'Название на языке'),
('lang.nativeName', 'uz', 'O‘z tilidagi nomi'),
('lang.nativeName', 'fr', 'Nom natif'),
('login.highlightSecure', 'en', 'HttpOnly cookie sessions, no tokens in the browser'),
('login.highlightSecure', 'ru', 'Сессии в HttpOnly cookie, без токенов в браузере'),
('login.highlightSecure', 'uz', 'HttpOnly cookie sessiyalari, brauzerda tokenlar saqlanmaydi'),
('login.highlightSecure', 'fr', 'Sessions par cookie HttpOnly, aucun jeton dans le navigateur'),
('login.highlightWorkflow', 'en', 'Draft, review and publish services with a full audit trail'),
('login.highlightWorkflow', 'ru', 'Черновики, проверка и публикация услуг с полным журналом аудита'),
('login.highlightWorkflow', 'uz', 'Xizmatlarni to‘liq audit tarixi bilan yaratish, tekshirish va e’lon qilish'),
('login.highlightWorkflow', 'fr', 'Rédigez, relisez et publiez les services avec un journal d’audit complet'),
('login.highlightLanguages', 'en', 'Catalogue content in every enabled language'),
('login.highlightLanguages', 'ru', 'Содержимое каталога на всех включённых языках'),
('login.highlightLanguages', 'uz', 'Katalog mazmuni barcha yoqilgan tillarda'),
('login.highlightLanguages', 'fr', 'Contenu du catalogue dans toutes les langues activées'),
('nav.collapse', 'en', 'Collapse sidebar'),
('nav.collapse', 'ru', 'Свернуть панель'),
('nav.collapse', 'uz', 'Panelni yig‘ish'),
('nav.collapse', 'fr', 'Réduire le panneau'),
('nav.expand', 'en', 'Expand sidebar'),
('nav.expand', 'ru', 'Развернуть панель'),
('nav.expand', 'uz', 'Panelni yoyish'),
('nav.expand', 'fr', 'Déployer le panneau'),
('orgs.namePlaceholder', 'en', 'Ministry of Justice'),
('orgs.namePlaceholder', 'ru', 'Министерство юстиции'),
('orgs.namePlaceholder', 'uz', 'Adliya vazirligi'),
('orgs.namePlaceholder', 'fr', 'Ministère de la Justice'),
('roles.custom', 'en', 'Custom role'),
('roles.custom', 'ru', 'Пользовательская роль'),
('roles.custom', 'uz', 'Maxsus rol'),
('roles.custom', 'fr', 'Rôle personnalisé'),
('roles.nameHint', 'en', 'For example CATALOG_EDITOR; permissions are assigned afterwards'),
('roles.nameHint', 'ru', 'Например CATALOG_EDITOR; разрешения назначаются позже'),
('roles.nameHint', 'uz', 'Masalan CATALOG_EDITOR; ruxsatlar keyin biriktiriladi'),
('roles.nameHint', 'fr', 'Par exemple CATALOG_EDITOR ; les permissions sont attribuées ensuite'),
('roles.system', 'en', 'System role'),
('roles.system', 'ru', 'Системная роль'),
('roles.system', 'uz', 'Tizim roli'),
('roles.system', 'fr', 'Rôle système'),
('roles.uncategorized', 'en', 'Other'),
('roles.uncategorized', 'ru', 'Прочее'),
('roles.uncategorized', 'uz', 'Boshqa'),
('roles.uncategorized', 'fr', 'Autre'),
('staff.keepOrganization', 'en', 'Keep current organization'),
('staff.keepOrganization', 'ru', 'Оставить текущую организацию'),
('staff.keepOrganization', 'uz', 'Joriy tashkilotni saqlab qolish'),
('staff.keepOrganization', 'fr', 'Conserver l’organisation actuelle'),
('state.errorText', 'en', 'Something went wrong while loading this page. Please try again.'),
('state.errorText', 'ru', 'При загрузке страницы произошла ошибка. Попробуйте ещё раз.'),
('state.errorText', 'uz', 'Sahifani yuklashda xatolik yuz berdi. Qayta urinib ko‘ring.'),
('state.errorText', 'fr', 'Une erreur est survenue lors du chargement de la page. Réessayez.'),
('state.networkError', 'en', 'No network connection'),
('state.networkError', 'ru', 'Нет соединения с сетью'),
('state.networkError', 'uz', 'Tarmoq bilan aloqa yo‘q'),
('state.networkError', 'fr', 'Pas de connexion réseau'),
('theme.toggle', 'en', 'Change theme'),
('theme.toggle', 'ru', 'Сменить тему'),
('theme.toggle', 'uz', 'Mavzuni o‘zgartirish'),
('theme.toggle', 'fr', 'Changer de thème'),
('theme.light', 'en', 'Light'),
('theme.light', 'ru', 'Светлая'),
('theme.light', 'uz', 'Yorug‘'),
('theme.light', 'fr', 'Clair'),
('theme.dark', 'en', 'Dark'),
('theme.dark', 'ru', 'Тёмная'),
('theme.dark', 'uz', 'Qorong‘i'),
('theme.dark', 'fr', 'Sombre'),
('theme.system', 'en', 'System'),
('theme.system', 'ru', 'Системная'),
('theme.system', 'uz', 'Tizim'),
('theme.system', 'fr', 'Système');
INSERT INTO translation_keys (translation_key, required, active)
SELECT DISTINCT key, TRUE, TRUE FROM frontend_redesign_labels ON CONFLICT (translation_key) DO NOTHING;
INSERT INTO translations (translation_key_id, language_code, translation_value)
SELECT k.id, s.lang, s.value FROM frontend_redesign_labels s JOIN translation_keys k ON k.translation_key = s.key
ON CONFLICT (language_code, translation_key_id) DO NOTHING;
