CREATE TEMPORARY TABLE public_catalog_labels (key VARCHAR(150), lang VARCHAR(64), value TEXT) ON COMMIT DROP;
INSERT INTO public_catalog_labels VALUES
('a11y.opensInNewTab', 'en', 'opens in a new tab'),
('a11y.opensInNewTab', 'ru', 'откроется в новой вкладке'),
('a11y.opensInNewTab', 'uz', 'yangi oynada ochiladi'),
('a11y.opensInNewTab', 'fr', 's’ouvre dans un nouvel onglet'),
('nav.finder', 'en', 'Service finder'),
('nav.finder', 'ru', 'Подбор услуги'),
('nav.finder', 'uz', 'Xizmatni topish'),
('nav.finder', 'fr', 'Trouver un service'),
('nav.saved', 'en', 'Saved'),
('nav.saved', 'ru', 'Сохранённые'),
('nav.saved', 'uz', 'Saqlanganlar'),
('nav.saved', 'fr', 'Enregistrés'),
('nav.reports', 'en', 'Reports'),
('nav.reports', 'ru', 'Сообщения'),
('nav.reports', 'uz', 'Xabarlar'),
('nav.reports', 'fr', 'Signalements'),
('contact.title', 'en', 'Contact and visiting information'),
('contact.title', 'ru', 'Контакты и приём посетителей'),
('contact.title', 'uz', 'Aloqa va qabul ma’lumotlari'),
('contact.title', 'fr', 'Coordonnées et accueil'),
('contact.address', 'en', 'Address'),
('contact.address', 'ru', 'Адрес'),
('contact.address', 'uz', 'Manzil'),
('contact.address', 'fr', 'Adresse'),
('contact.region', 'en', 'Region'),
('contact.region', 'ru', 'Регион'),
('contact.region', 'uz', 'Hudud'),
('contact.region', 'fr', 'Région'),
('contact.regionNone', 'en', 'Not specified'),
('contact.regionNone', 'ru', 'Не указан'),
('contact.regionNone', 'uz', 'Ko‘rsatilmagan'),
('contact.regionNone', 'fr', 'Non précisée'),
('contact.phone', 'en', 'Phone'),
('contact.phone', 'ru', 'Телефон'),
('contact.phone', 'uz', 'Telefon'),
('contact.phone', 'fr', 'Téléphone'),
('contact.workingHours', 'en', 'Working hours'),
('contact.workingHours', 'ru', 'Часы работы'),
('contact.workingHours', 'uz', 'Ish vaqti'),
('contact.workingHours', 'fr', 'Horaires d’ouverture'),
('contact.latitude', 'en', 'Latitude'),
('contact.latitude', 'ru', 'Широта'),
('contact.latitude', 'uz', 'Kenglik'),
('contact.latitude', 'fr', 'Latitude'),
('contact.longitude', 'en', 'Longitude'),
('contact.longitude', 'ru', 'Долгота'),
('contact.longitude', 'uz', 'Uzunlik'),
('contact.longitude', 'fr', 'Longitude'),
('contact.map', 'en', 'Map'),
('contact.map', 'ru', 'Карта'),
('contact.map', 'uz', 'Xarita'),
('contact.map', 'fr', 'Carte'),
('contact.mapUrl', 'en', 'Map link'),
('contact.mapUrl', 'ru', 'Ссылка на карту'),
('contact.mapUrl', 'uz', 'Xarita havolasi'),
('contact.mapUrl', 'fr', 'Lien vers la carte'),
('contact.mapUrlHint', 'en', 'Optional link to a free map page. Do not use links that need an API key.'),
('contact.mapUrlHint', 'ru', 'Необязательная ссылка на бесплатную страницу карты. Не используйте ссылки, требующие ключ API.'),
('contact.mapUrlHint', 'uz', 'Bepul xarita sahifasiga ixtiyoriy havola. API kaliti talab qilinadigan havolalardan foydalanmang.'),
('contact.mapUrlHint', 'fr', 'Lien facultatif vers une page de carte gratuite. N’utilisez pas de liens nécessitant une clé d’API.'),
('contact.mapLink', 'en', 'Open the map link'),
('contact.mapLink', 'ru', 'Открыть ссылку на карту'),
('contact.mapLink', 'uz', 'Xarita havolasini ochish'),
('contact.mapLink', 'fr', 'Ouvrir le lien de la carte'),
('contact.openStreetMap', 'en', 'Open in OpenStreetMap'),
('contact.openStreetMap', 'ru', 'Открыть в OpenStreetMap'),
('contact.openStreetMap', 'uz', 'OpenStreetMap’da ochish'),
('contact.openStreetMap', 'fr', 'Ouvrir dans OpenStreetMap'),
('contact.notProvided', 'en', 'Not provided yet'),
('contact.notProvided', 'ru', 'Пока не указано'),
('contact.notProvided', 'uz', 'Hozircha ko‘rsatilmagan'),
('contact.notProvided', 'fr', 'Pas encore renseigné'),
('contact.editorHint', 'en', 'Enter only officially published details. Leave unknown fields empty; the public page shows them as not provided.'),
('contact.editorHint', 'ru', 'Указывайте только официально опубликованные сведения. Неизвестные поля оставьте пустыми — на публичной странице они будут отмечены как неуказанные.'),
('contact.editorHint', 'uz', 'Faqat rasman e’lon qilingan ma’lumotlarni kiriting. Noma’lum maydonlarni bo‘sh qoldiring — ochiq sahifada ular ko‘rsatilmagan deb belgilanadi.'),
('contact.editorHint', 'fr', 'Saisissez uniquement des informations publiées officiellement. Laissez vides les champs inconnus : la page publique les indique comme non renseignés.'),
('finder.cta', 'en', 'Find a service step by step'),
('finder.cta', 'ru', 'Подобрать услугу по шагам'),
('finder.cta', 'uz', 'Xizmatni bosqichma-bosqich topish'),
('finder.cta', 'fr', 'Trouver un service étape par étape'),
('finder.eyebrow', 'en', 'Service finder'),
('finder.eyebrow', 'ru', 'Подбор услуги'),
('finder.eyebrow', 'uz', 'Xizmatni topish'),
('finder.eyebrow', 'fr', 'Trouver un service'),
('finder.title', 'en', 'Find the right service step by step'),
('finder.title', 'ru', 'Найдите нужную услугу по шагам'),
('finder.title', 'uz', 'Kerakli xizmatni bosqichma-bosqich toping'),
('finder.title', 'fr', 'Trouvez le bon service étape par étape'),
('finder.subtitle', 'en', 'Answer up to three short questions. Nothing you enter is sent or stored, and you do not need an account.'),
('finder.subtitle', 'ru', 'Ответьте не более чем на три коротких вопроса. Введённые данные никуда не отправляются и не сохраняются, учётная запись не нужна.'),
('finder.subtitle', 'uz', 'Uchtagacha qisqa savolga javob bering. Kiritilgan ma’lumotlar hech qayerga yuborilmaydi va saqlanmaydi, hisob qaydnomasi kerak emas.'),
('finder.subtitle', 'fr', 'Répondez au plus à trois courtes questions. Rien de ce que vous saisissez n’est envoyé ni conservé, et aucun compte n’est nécessaire.'),
('finder.progress', 'en', 'Progress'),
('finder.progress', 'ru', 'Ход подбора'),
('finder.progress', 'uz', 'Jarayon'),
('finder.progress', 'fr', 'Progression'),
('finder.stepSituation', 'en', 'Situation'),
('finder.stepSituation', 'ru', 'Ситуация'),
('finder.stepSituation', 'uz', 'Vaziyat'),
('finder.stepSituation', 'fr', 'Situation'),
('finder.stepGoal', 'en', 'Goal'),
('finder.stepGoal', 'ru', 'Цель'),
('finder.stepGoal', 'uz', 'Maqsad'),
('finder.stepGoal', 'fr', 'Objectif'),
('finder.stepOrganization', 'en', 'Organization'),
('finder.stepOrganization', 'ru', 'Организация'),
('finder.stepOrganization', 'uz', 'Tashkilot'),
('finder.stepOrganization', 'fr', 'Organisation'),
('finder.stepResults', 'en', 'Results'),
('finder.stepResults', 'ru', 'Результаты'),
('finder.stepResults', 'uz', 'Natijalar'),
('finder.stepResults', 'fr', 'Résultats'),
('finder.situationQuestion', 'en', 'What is your situation?'),
('finder.situationQuestion', 'ru', 'Какая у вас ситуация?'),
('finder.situationQuestion', 'uz', 'Sizning vaziyatingiz qanday?'),
('finder.situationQuestion', 'fr', 'Quelle est votre situation ?'),
('finder.situationHint', 'en', 'Choose the area of life your question belongs to.'),
('finder.situationHint', 'ru', 'Выберите сферу жизни, к которой относится ваш вопрос.'),
('finder.situationHint', 'uz', 'Savolingiz tegishli bo‘lgan hayot sohasini tanlang.'),
('finder.situationHint', 'fr', 'Choisissez le domaine de la vie concerné par votre question.'),
('finder.anySituation', 'en', 'I am not sure / show all areas'),
('finder.anySituation', 'ru', 'Не уверен(а) — показать все сферы'),
('finder.anySituation', 'uz', 'Aniq bilmayman — barcha sohalarni ko‘rsatish'),
('finder.anySituation', 'fr', 'Je ne sais pas — afficher tous les domaines'),
('finder.goalQuestion', 'en', 'What do you want to do?'),
('finder.goalQuestion', 'ru', 'Что вы хотите сделать?'),
('finder.goalQuestion', 'uz', 'Nima qilmoqchisiz?'),
('finder.goalQuestion', 'fr', 'Que souhaitez-vous faire ?'),
('finder.goalLabel', 'en', 'Describe your goal in a few words (optional)'),
('finder.goalLabel', 'ru', 'Опишите цель в нескольких словах (необязательно)'),
('finder.goalLabel', 'uz', 'Maqsadingizni bir necha so‘z bilan yozing (ixtiyoriy)'),
('finder.goalLabel', 'fr', 'Décrivez votre objectif en quelques mots (facultatif)'),
('finder.goalHint', 'en', 'For example: certificate, registration, duplicate. Leave it empty to see every service in this area.'),
('finder.goalHint', 'ru', 'Например: справка, регистрация, дубликат. Оставьте поле пустым, чтобы увидеть все услуги этой сферы.'),
('finder.goalHint', 'uz', 'Masalan: ma’lumotnoma, ro‘yxatdan o‘tkazish, dublikat. Ushbu sohadagi barcha xizmatlarni ko‘rish uchun bo‘sh qoldiring.'),
('finder.goalHint', 'fr', 'Par exemple : certificat, enregistrement, duplicata. Laissez vide pour voir tous les services de ce domaine.'),
('finder.examples', 'en', 'Services in this area'),
('finder.examples', 'ru', 'Услуги в этой сфере'),
('finder.examples', 'uz', 'Ushbu sohadagi xizmatlar'),
('finder.examples', 'fr', 'Services de ce domaine'),
('finder.organizationQuestion', 'en', 'Do you already know the organization?'),
('finder.organizationQuestion', 'ru', 'Вы уже знаете организацию?'),
('finder.organizationQuestion', 'uz', 'Tashkilotni bilasizmi?'),
('finder.organizationQuestion', 'fr', 'Connaissez-vous déjà l’organisation ?'),
('finder.organizationHint', 'en', 'Only organizations with matching services are listed.'),
('finder.organizationHint', 'ru', 'Показаны только организации с подходящими услугами.'),
('finder.organizationHint', 'uz', 'Faqat mos xizmatlari bor tashkilotlar ko‘rsatilgan.'),
('finder.organizationHint', 'fr', 'Seules les organisations proposant des services correspondants sont listées.'),
('finder.anyOrganization', 'en', 'Any organization'),
('finder.anyOrganization', 'ru', 'Любая организация'),
('finder.anyOrganization', 'uz', 'Istalgan tashkilot'),
('finder.anyOrganization', 'fr', 'N’importe quelle organisation'),
('finder.resultsTitle', 'en', 'Services that match your answers'),
('finder.resultsTitle', 'ru', 'Услуги, подходящие под ваши ответы'),
('finder.resultsTitle', 'uz', 'Javoblaringizga mos xizmatlar'),
('finder.resultsTitle', 'fr', 'Services correspondant à vos réponses'),
('finder.matching', 'en', 'services match your answers so far'),
('finder.matching', 'ru', 'услуг соответствуют вашим ответам'),
('finder.matching', 'uz', 'ta xizmat javoblaringizga mos keladi'),
('finder.matching', 'fr', 'services correspondent à vos réponses pour l’instant'),
('finder.servicesShort', 'en', 'services'),
('finder.servicesShort', 'ru', 'услуг'),
('finder.servicesShort', 'uz', 'ta xizmat'),
('finder.servicesShort', 'fr', 'services'),
('finder.next', 'en', 'Next'),
('finder.next', 'ru', 'Далее'),
('finder.next', 'uz', 'Keyingisi'),
('finder.next', 'fr', 'Suivant'),
('finder.showResults', 'en', 'Show services'),
('finder.showResults', 'ru', 'Показать услуги'),
('finder.showResults', 'uz', 'Xizmatlarni ko‘rsatish'),
('finder.showResults', 'fr', 'Afficher les services'),
('finder.restart', 'en', 'Start over'),
('finder.restart', 'ru', 'Начать заново'),
('finder.restart', 'uz', 'Qaytadan boshlash'),
('finder.restart', 'fr', 'Recommencer'),
('finder.noResultsTitle', 'en', 'No published services match these answers'),
('finder.noResultsTitle', 'ru', 'Нет опубликованных услуг, подходящих под эти ответы'),
('finder.noResultsTitle', 'uz', 'Ushbu javoblarga mos e’lon qilingan xizmatlar yo‘q'),
('finder.noResultsTitle', 'fr', 'Aucun service publié ne correspond à ces réponses'),
('finder.noResultsText', 'en', 'Try fewer keywords, another situation or any organization.'),
('finder.noResultsText', 'ru', 'Попробуйте меньше ключевых слов, другую ситуацию или любую организацию.'),
('finder.noResultsText', 'uz', 'Kamroq kalit so‘z, boshqa vaziyat yoki istalgan tashkilotni tanlab ko‘ring.'),
('finder.noResultsText', 'fr', 'Essayez moins de mots-clés, une autre situation ou n’importe quelle organisation.'),
('finder.clearGoal', 'en', 'Clear keywords'),
('finder.clearGoal', 'ru', 'Очистить ключевые слова'),
('finder.clearGoal', 'uz', 'Kalit so‘zlarni tozalash'),
('finder.clearGoal', 'fr', 'Effacer les mots-clés'),
('finder.otherSituation', 'en', 'Choose another situation'),
('finder.otherSituation', 'ru', 'Выбрать другую ситуацию'),
('finder.otherSituation', 'uz', 'Boshqa vaziyatni tanlash'),
('finder.otherSituation', 'fr', 'Choisir une autre situation'),
('finder.browseAll', 'en', 'Browse the full catalogue'),
('finder.browseAll', 'ru', 'Открыть весь каталог'),
('finder.browseAll', 'uz', 'To‘liq katalogni ko‘rish'),
('finder.browseAll', 'fr', 'Parcourir tout le catalogue'),
('finder.emptyCatalogTitle', 'en', 'No services are published yet'),
('finder.emptyCatalogTitle', 'ru', 'Опубликованных услуг пока нет'),
('finder.emptyCatalogTitle', 'uz', 'Hozircha e’lon qilingan xizmatlar yo‘q'),
('finder.emptyCatalogTitle', 'fr', 'Aucun service n’est encore publié'),
('finder.emptyCatalogText', 'en', 'Please check again later or browse the organizations.'),
('finder.emptyCatalogText', 'ru', 'Загляните позже или посмотрите список организаций.'),
('finder.emptyCatalogText', 'uz', 'Keyinroq qayta tekshiring yoki tashkilotlar ro‘yxatini ko‘ring.'),
('finder.emptyCatalogText', 'fr', 'Revenez plus tard ou consultez la liste des organisations.'),
('fn.machineTranslated', 'en', 'Parts of this page were translated automatically and may contain mistakes.'),
('fn.machineTranslated', 'ru', 'Часть текста на этой странице переведена автоматически и может содержать ошибки.'),
('fn.machineTranslated', 'uz', 'Ushbu sahifaning bir qismi avtomatik tarjima qilingan va xatolar bo‘lishi mumkin.'),
('fn.machineTranslated', 'fr', 'Certaines parties de cette page ont été traduites automatiquement et peuvent contenir des erreurs.'),
('fn.originalLanguageShown', 'en', 'Some details are shown in the original language because a translation is not available yet.'),
('fn.originalLanguageShown', 'ru', 'Некоторые сведения показаны на языке оригинала, потому что перевода пока нет.'),
('fn.originalLanguageShown', 'uz', 'Ayrim ma’lumotlar asl tilda ko‘rsatilgan, chunki tarjimasi hali yo‘q.'),
('fn.originalLanguageShown', 'fr', 'Certaines informations sont affichées dans la langue d’origine, faute de traduction disponible.'),
('fnAdmin.originalText', 'en', 'Original'),
('fnAdmin.originalText', 'ru', 'Оригинал'),
('fnAdmin.originalText', 'uz', 'Asl matn'),
('fnAdmin.originalText', 'fr', 'Original'),
('fnAdmin.action.VERIFY', 'en', 'Verified'),
('fnAdmin.action.VERIFY', 'ru', 'Проверено'),
('fnAdmin.action.VERIFY', 'uz', 'Tekshirildi'),
('fnAdmin.action.VERIFY', 'fr', 'Vérifié'),
('fnAdmin.action.REPORT_RECEIVED', 'en', 'Report received'),
('fnAdmin.action.REPORT_RECEIVED', 'ru', 'Получено сообщение'),
('fnAdmin.action.REPORT_RECEIVED', 'uz', 'Xabar qabul qilindi'),
('fnAdmin.action.REPORT_RECEIVED', 'fr', 'Signalement reçu'),
('fnAdmin.action.REPORT_STATUS_CHANGE', 'en', 'Report status changed'),
('fnAdmin.action.REPORT_STATUS_CHANGE', 'ru', 'Статус сообщения изменён'),
('fnAdmin.action.REPORT_STATUS_CHANGE', 'uz', 'Xabar holati o‘zgartirildi'),
('fnAdmin.action.REPORT_STATUS_CHANGE', 'fr', 'Statut du signalement modifié'),
('instructions.atAGlance', 'en', 'At a glance'),
('instructions.atAGlance', 'ru', 'Коротко'),
('instructions.atAGlance', 'uz', 'Qisqacha'),
('instructions.atAGlance', 'fr', 'En bref'),
('instructions.whoCanUse', 'en', 'Who can use this service'),
('instructions.whoCanUse', 'ru', 'Кто может воспользоваться услугой'),
('instructions.whoCanUse', 'uz', 'Xizmatdan kim foydalanishi mumkin'),
('instructions.whoCanUse', 'fr', 'Qui peut utiliser ce service'),
('instructions.steps', 'en', 'Step-by-step procedure'),
('instructions.steps', 'ru', 'Порядок действий'),
('instructions.steps', 'uz', 'Bosqichma-bosqich tartib'),
('instructions.steps', 'fr', 'Procédure étape par étape'),
('instructions.requiredDocuments', 'en', 'Required documents'),
('instructions.requiredDocuments', 'ru', 'Необходимые документы'),
('instructions.requiredDocuments', 'uz', 'Kerakli hujjatlar'),
('instructions.requiredDocuments', 'fr', 'Documents requis'),
('instructions.whereHowToApply', 'en', 'Where and how to apply'),
('instructions.whereHowToApply', 'ru', 'Где и как обратиться'),
('instructions.whereHowToApply', 'uz', 'Qayerga va qanday murojaat qilish'),
('instructions.whereHowToApply', 'fr', 'Où et comment faire la demande'),
('instructions.processingTime', 'en', 'Processing time'),
('instructions.processingTime', 'ru', 'Срок оказания'),
('instructions.processingTime', 'uz', 'Ko‘rib chiqish muddati'),
('instructions.processingTime', 'fr', 'Délai de traitement'),
('instructions.fee', 'en', 'Official fee'),
('instructions.fee', 'ru', 'Официальная плата'),
('instructions.fee', 'uz', 'Rasmiy to‘lov'),
('instructions.fee', 'fr', 'Frais officiels'),
('instructions.additionalRequirements', 'en', 'Additional requirements'),
('instructions.additionalRequirements', 'ru', 'Дополнительные требования'),
('instructions.additionalRequirements', 'uz', 'Qo‘shimcha talablar'),
('instructions.additionalRequirements', 'fr', 'Exigences supplémentaires'),
('instructions.notProvided', 'en', 'Not provided yet. Confirm with the organization before you apply.'),
('instructions.notProvided', 'ru', 'Пока не указано. Уточните в организации перед обращением.'),
('instructions.notProvided', 'uz', 'Hozircha ko‘rsatilmagan. Murojaat qilishdan oldin tashkilotdan aniqlang.'),
('instructions.notProvided', 'fr', 'Pas encore renseigné. Vérifiez auprès de l’organisation avant de faire votre demande.'),
('instructions.notSpecified', 'en', 'Not specified'),
('instructions.notSpecified', 'ru', 'Не указано'),
('instructions.notSpecified', 'uz', 'Ko‘rsatilmagan'),
('instructions.notSpecified', 'fr', 'Non précisé'),
('instructions.editorTitle', 'en', 'Structured instructions'),
('instructions.editorTitle', 'ru', 'Структурированная инструкция'),
('instructions.editorTitle', 'uz', 'Tuzilgan yo‘riqnoma'),
('instructions.editorTitle', 'fr', 'Instructions structurées'),
('instructions.editorHint', 'en', 'Fill in only what the official source confirms. Leave a field empty if it is unknown; visitors will see that it is not provided yet.'),
('instructions.editorHint', 'ru', 'Заполняйте только то, что подтверждает официальный источник. Если сведения неизвестны, оставьте поле пустым — посетители увидят, что они пока не указаны.'),
('instructions.editorHint', 'uz', 'Faqat rasmiy manba tasdiqlagan ma’lumotlarni kiriting. Noma’lum bo‘lsa, maydonni bo‘sh qoldiring — foydalanuvchilar u hali ko‘rsatilmaganini ko‘radi.'),
('instructions.editorHint', 'fr', 'Ne renseignez que ce que confirme la source officielle. Laissez un champ vide s’il est inconnu : les visiteurs verront qu’il n’est pas encore renseigné.'),
('instructions.oneItemPerLine', 'en', 'One item per line.'),
('instructions.oneItemPerLine', 'ru', 'Один пункт на строку.'),
('instructions.oneItemPerLine', 'uz', 'Har bir qatorda bitta band.'),
('instructions.oneItemPerLine', 'fr', 'Un élément par ligne.'),
('print.action', 'en', 'Print'),
('print.action', 'ru', 'Печать'),
('print.action', 'uz', 'Chop etish'),
('print.action', 'fr', 'Imprimer'),
('print.checklist', 'en', 'Print checklist'),
('print.checklist', 'ru', 'Распечатать памятку'),
('print.checklist', 'uz', 'Eslatmani chop etish'),
('print.checklist', 'fr', 'Imprimer la liste'),
('print.printedOn', 'en', 'Printed on'),
('print.printedOn', 'ru', 'Распечатано'),
('print.printedOn', 'uz', 'Chop etilgan sana'),
('print.printedOn', 'fr', 'Imprimé le'),
('report.open', 'en', 'Report a problem'),
('report.open', 'ru', 'Сообщить об ошибке'),
('report.open', 'uz', 'Xato haqida xabar berish'),
('report.open', 'fr', 'Signaler un problème'),
('report.title', 'en', 'Report incorrect or outdated information'),
('report.title', 'ru', 'Сообщить о неверной или устаревшей информации'),
('report.title', 'uz', 'Noto‘g‘ri yoki eskirgan ma’lumot haqida xabar berish'),
('report.title', 'fr', 'Signaler une information erronée ou obsolète'),
('report.intro', 'en', 'Tell us what is wrong on this page. You do not need an account.'),
('report.intro', 'ru', 'Расскажите, что на этой странице не так. Учётная запись не нужна.'),
('report.intro', 'uz', 'Ushbu sahifada nima noto‘g‘ri ekanini yozing. Hisob qaydnomasi kerak emas.'),
('report.intro', 'fr', 'Indiquez-nous ce qui ne va pas sur cette page. Aucun compte n’est nécessaire.'),
('report.category', 'en', 'What is wrong?'),
('report.category', 'ru', 'Что не так?'),
('report.category', 'uz', 'Nima noto‘g‘ri?'),
('report.category', 'fr', 'Quel est le problème ?'),
('report.description', 'en', 'Describe the problem'),
('report.description', 'ru', 'Опишите проблему'),
('report.description', 'uz', 'Muammoni tasvirlab bering'),
('report.description', 'fr', 'Décrivez le problème'),
('report.descriptionHint', 'en', 'Say what is wrong and, if you know it, where the correct information is published.'),
('report.descriptionHint', 'ru', 'Укажите, что неверно, и, если знаете, где опубликована правильная информация.'),
('report.descriptionHint', 'uz', 'Nima noto‘g‘ri ekanini va, agar bilsangiz, to‘g‘ri ma’lumot qayerda e’lon qilinganini yozing.'),
('report.descriptionHint', 'fr', 'Précisez ce qui est erroné et, si vous le savez, où l’information correcte est publiée.'),
('report.descriptionTooShort', 'en', 'Describe the problem in at least 10 characters'),
('report.descriptionTooShort', 'ru', 'Опишите проблему не короче 10 символов'),
('report.descriptionTooShort', 'uz', 'Muammoni kamida 10 ta belgida tasvirlang'),
('report.descriptionTooShort', 'fr', 'Décrivez le problème en au moins 10 caractères'),
('report.contact', 'en', 'Email or phone for questions'),
('report.contact', 'ru', 'Email или телефон для уточнений'),
('report.contact', 'uz', 'Savollar uchun email yoki telefon'),
('report.contact', 'fr', 'E-mail ou téléphone pour vous recontacter'),
('report.contactHint', 'en', 'Optional. Only staff handling the report can see it, and it is deleted when the report is closed.'),
('report.contactHint', 'ru', 'Необязательно. Видно только сотрудникам, которые рассматривают сообщение, и удаляется после его закрытия.'),
('report.contactHint', 'uz', 'Ixtiyoriy. Uni faqat xabarni ko‘rib chiqayotgan xodimlar ko‘radi va xabar yopilganda o‘chiriladi.'),
('report.contactHint', 'fr', 'Facultatif. Seul le personnel qui traite le signalement peut le voir, et il est supprimé à la clôture du signalement.'),
('report.contactInvalid', 'en', 'Enter an email address or a phone number, or leave the field empty'),
('report.contactInvalid', 'ru', 'Укажите email или номер телефона либо оставьте поле пустым'),
('report.contactInvalid', 'uz', 'Email yoki telefon raqamini kiriting yoki maydonni bo‘sh qoldiring'),
('report.contactInvalid', 'fr', 'Saisissez une adresse e-mail ou un numéro de téléphone, ou laissez le champ vide'),
('report.honeypot', 'en', 'Leave this field empty'),
('report.honeypot', 'ru', 'Оставьте это поле пустым'),
('report.honeypot', 'uz', 'Bu maydonni bo‘sh qoldiring'),
('report.honeypot', 'fr', 'Laissez ce champ vide'),
('report.privacy', 'en', 'Do not include personal documents or ID numbers. Reports are private and never change the page automatically.'),
('report.privacy', 'ru', 'Не указывайте личные документы и идентификационные номера. Сообщения не публикуются и не меняют страницу автоматически.'),
('report.privacy', 'uz', 'Shaxsiy hujjatlar va identifikatsiya raqamlarini yozmang. Xabarlar ommaga ko‘rsatilmaydi va sahifani avtomatik o‘zgartirmaydi.'),
('report.privacy', 'fr', 'N’indiquez ni documents personnels ni numéros d’identité. Les signalements restent privés et ne modifient jamais la page automatiquement.'),
('report.send', 'en', 'Send report'),
('report.send', 'ru', 'Отправить'),
('report.send', 'uz', 'Yuborish'),
('report.send', 'fr', 'Envoyer le signalement'),
('report.thanksTitle', 'en', 'Thank you, your report was sent'),
('report.thanksTitle', 'ru', 'Спасибо, сообщение отправлено'),
('report.thanksTitle', 'uz', 'Rahmat, xabaringiz yuborildi'),
('report.thanksTitle', 'fr', 'Merci, votre signalement a été envoyé'),
('report.thanksText', 'en', 'Editors will check it against official sources. Public information changes only after their review.'),
('report.thanksText', 'ru', 'Редакторы сверят его с официальными источниками. Публичная информация меняется только после их проверки.'),
('report.thanksText', 'uz', 'Muharrirlar uni rasmiy manbalar bilan solishtiradi. Ochiq ma’lumot faqat ular tekshirgandan keyin o‘zgaradi.'),
('report.thanksText', 'fr', 'Les éditeurs le compareront aux sources officielles. Les informations publiques ne changent qu’après leur vérification.'),
('report.rateLimited', 'en', 'Too many reports were sent from your connection. Please try again later.'),
('report.rateLimited', 'ru', 'С вашего подключения отправлено слишком много сообщений. Попробуйте позже.'),
('report.rateLimited', 'uz', 'Ulanishingizdan juda ko‘p xabar yuborildi. Keyinroq qayta urinib ko‘ring.'),
('report.rateLimited', 'fr', 'Trop de signalements ont été envoyés depuis votre connexion. Réessayez plus tard.'),
('report.notAvailable', 'en', 'This page is no longer published, so it cannot be reported.'),
('report.notAvailable', 'ru', 'Эта страница больше не опубликована, поэтому сообщить о ней нельзя.'),
('report.notAvailable', 'uz', 'Bu sahifa endi e’lon qilinmagan, shuning uchun u haqida xabar berib bo‘lmaydi.'),
('report.notAvailable', 'fr', 'Cette page n’est plus publiée et ne peut donc pas être signalée.'),
('report.category.INCORRECT_INFORMATION', 'en', 'Information is incorrect'),
('report.category.INCORRECT_INFORMATION', 'ru', 'Информация неверна'),
('report.category.INCORRECT_INFORMATION', 'uz', 'Ma’lumot noto‘g‘ri'),
('report.category.INCORRECT_INFORMATION', 'fr', 'L’information est erronée'),
('report.category.OUTDATED_INFORMATION', 'en', 'Information is outdated'),
('report.category.OUTDATED_INFORMATION', 'ru', 'Информация устарела'),
('report.category.OUTDATED_INFORMATION', 'uz', 'Ma’lumot eskirgan'),
('report.category.OUTDATED_INFORMATION', 'fr', 'L’information est obsolète'),
('report.category.DOCUMENTS_OR_STEPS', 'en', 'Documents or steps are wrong'),
('report.category.DOCUMENTS_OR_STEPS', 'ru', 'Неверные документы или порядок действий'),
('report.category.DOCUMENTS_OR_STEPS', 'uz', 'Hujjatlar yoki bosqichlar noto‘g‘ri'),
('report.category.DOCUMENTS_OR_STEPS', 'fr', 'Documents ou étapes erronés'),
('report.category.FEES_OR_TIMING', 'en', 'Fee or processing time is wrong'),
('report.category.FEES_OR_TIMING', 'ru', 'Неверная плата или срок'),
('report.category.FEES_OR_TIMING', 'uz', 'To‘lov yoki muddat noto‘g‘ri'),
('report.category.FEES_OR_TIMING', 'fr', 'Frais ou délai erronés'),
('report.category.CONTACT_DETAILS', 'en', 'Address, phone or hours are wrong'),
('report.category.CONTACT_DETAILS', 'ru', 'Неверный адрес, телефон или часы работы'),
('report.category.CONTACT_DETAILS', 'uz', 'Manzil, telefon yoki ish vaqti noto‘g‘ri'),
('report.category.CONTACT_DETAILS', 'fr', 'Adresse, téléphone ou horaires erronés'),
('report.category.BROKEN_LINK', 'en', 'A link does not work'),
('report.category.BROKEN_LINK', 'ru', 'Ссылка не работает'),
('report.category.BROKEN_LINK', 'uz', 'Havola ishlamayapti'),
('report.category.BROKEN_LINK', 'fr', 'Un lien ne fonctionne pas'),
('report.category.TRANSLATION', 'en', 'Translation problem'),
('report.category.TRANSLATION', 'ru', 'Ошибка перевода'),
('report.category.TRANSLATION', 'uz', 'Tarjimadagi xato'),
('report.category.TRANSLATION', 'fr', 'Problème de traduction'),
('report.category.OTHER', 'en', 'Something else'),
('report.category.OTHER', 'ru', 'Другое'),
('report.category.OTHER', 'uz', 'Boshqa'),
('report.category.OTHER', 'fr', 'Autre chose'),
('reports.title', 'en', 'Information reports'),
('reports.title', 'ru', 'Сообщения об ошибках'),
('reports.title', 'uz', 'Xatolar haqidagi xabarlar'),
('reports.title', 'fr', 'Signalements d’information'),
('reports.subtitle', 'en', 'Visitor reports about incorrect or outdated information. Reports are private and never change public pages automatically.'),
('reports.subtitle', 'ru', 'Сообщения посетителей о неверной или устаревшей информации. Они не публикуются и не меняют страницы автоматически.'),
('reports.subtitle', 'uz', 'Tashrif buyuruvchilarning noto‘g‘ri yoki eskirgan ma’lumotlar haqidagi xabarlari. Ular ommaga ko‘rsatilmaydi va sahifalarni avtomatik o‘zgartirmaydi.'),
('reports.subtitle', 'fr', 'Signalements des visiteurs concernant des informations erronées ou obsolètes. Ils restent privés et ne modifient jamais les pages publiques automatiquement.'),
('reports.dashboardTitle', 'en', 'Open reports'),
('reports.dashboardTitle', 'ru', 'Открытые сообщения'),
('reports.dashboardTitle', 'uz', 'Ochiq xabarlar'),
('reports.dashboardTitle', 'fr', 'Signalements ouverts'),
('reports.received', 'en', 'Received'),
('reports.received', 'ru', 'Получено'),
('reports.received', 'uz', 'Qabul qilingan'),
('reports.received', 'fr', 'Reçu'),
('reports.subject', 'en', 'Subject'),
('reports.subject', 'ru', 'Объект'),
('reports.subject', 'uz', 'Obyekt'),
('reports.subject', 'fr', 'Objet'),
('reports.category', 'en', 'Problem'),
('reports.category', 'ru', 'Проблема'),
('reports.category', 'uz', 'Muammo'),
('reports.category', 'fr', 'Problème'),
('reports.type', 'en', 'Type'),
('reports.type', 'ru', 'Тип'),
('reports.type', 'uz', 'Turi'),
('reports.type', 'fr', 'Type'),
('reports.typeFunction', 'en', 'Service'),
('reports.typeFunction', 'ru', 'Услуга'),
('reports.typeFunction', 'uz', 'Xizmat'),
('reports.typeFunction', 'fr', 'Service'),
('reports.typeOrganization', 'en', 'Organization'),
('reports.typeOrganization', 'ru', 'Организация'),
('reports.typeOrganization', 'uz', 'Tashkilot'),
('reports.typeOrganization', 'fr', 'Organisation'),
('reports.review', 'en', 'Review'),
('reports.review', 'ru', 'Рассмотреть'),
('reports.review', 'uz', 'Ko‘rib chiqish'),
('reports.review', 'fr', 'Examiner'),
('reports.description', 'en', 'Report'),
('reports.description', 'ru', 'Сообщение'),
('reports.description', 'uz', 'Xabar'),
('reports.description', 'fr', 'Signalement'),
('reports.contact', 'en', 'Reporter contact'),
('reports.contact', 'ru', 'Контакт автора'),
('reports.contact', 'uz', 'Muallif bilan aloqa'),
('reports.contact', 'fr', 'Contact de l’auteur'),
('reports.noContact', 'en', 'The visitor did not leave contact details.'),
('reports.noContact', 'ru', 'Посетитель не оставил контактов.'),
('reports.noContact', 'uz', 'Tashrif buyuruvchi aloqa ma’lumotlarini qoldirmagan.'),
('reports.noContact', 'fr', 'Le visiteur n’a pas laissé de coordonnées.'),
('reports.contactErased', 'en', 'Not stored: contact details are deleted when a report is closed.'),
('reports.contactErased', 'ru', 'Не хранится: контакты удаляются при закрытии сообщения.'),
('reports.contactErased', 'uz', 'Saqlanmaydi: xabar yopilganda aloqa ma’lumotlari o‘chiriladi.'),
('reports.contactErased', 'fr', 'Non conservé : les coordonnées sont supprimées à la clôture du signalement.'),
('reports.openPublic', 'en', 'Open public page'),
('reports.openPublic', 'ru', 'Открыть публичную страницу'),
('reports.openPublic', 'uz', 'Ochiq sahifani ochish'),
('reports.openPublic', 'fr', 'Ouvrir la page publique'),
('reports.openEditor', 'en', 'Open in editor'),
('reports.openEditor', 'ru', 'Открыть в редакторе'),
('reports.openEditor', 'uz', 'Muharrirda ochish'),
('reports.openEditor', 'fr', 'Ouvrir dans l’éditeur'),
('reports.noAutoChange', 'en', 'Correct the information through the normal editing and review process. Changing the report status does not change the public page.'),
('reports.noAutoChange', 'ru', 'Исправляйте информацию через обычный процесс редактирования и проверки. Изменение статуса сообщения не меняет публичную страницу.'),
('reports.noAutoChange', 'uz', 'Ma’lumotni odatiy tahrirlash va tekshirish jarayoni orqali tuzating. Xabar holatini o‘zgartirish ochiq sahifani o‘zgartirmaydi.'),
('reports.noAutoChange', 'fr', 'Corrigez l’information via le processus habituel de modification et de relecture. Changer le statut du signalement ne modifie pas la page publique.'),
('reports.note', 'en', 'Internal note'),
('reports.note', 'ru', 'Внутренняя заметка'),
('reports.note', 'uz', 'Ichki izoh'),
('reports.note', 'fr', 'Note interne'),
('reports.noteHint', 'en', 'Visible to staff only.'),
('reports.noteHint', 'ru', 'Видна только сотрудникам.'),
('reports.noteHint', 'uz', 'Faqat xodimlarga ko‘rinadi.'),
('reports.noteHint', 'fr', 'Visible uniquement par le personnel.'),
('reports.emptyTitle', 'en', 'No reports here'),
('reports.emptyTitle', 'ru', 'Сообщений нет'),
('reports.emptyTitle', 'uz', 'Xabarlar yo‘q'),
('reports.emptyTitle', 'fr', 'Aucun signalement'),
('reports.emptyText', 'en', 'New reports from visitors will appear in this list.'),
('reports.emptyText', 'ru', 'Новые сообщения посетителей появятся в этом списке.'),
('reports.emptyText', 'uz', 'Tashrif buyuruvchilarning yangi xabarlari shu ro‘yxatda paydo bo‘ladi.'),
('reports.emptyText', 'fr', 'Les nouveaux signalements des visiteurs apparaîtront dans cette liste.'),
('reports.filteredByEntity', 'en', 'Showing reports for one item'),
('reports.filteredByEntity', 'ru', 'Показаны сообщения по одному объекту'),
('reports.filteredByEntity', 'uz', 'Bitta obyekt bo‘yicha xabarlar ko‘rsatilmoqda'),
('reports.filteredByEntity', 'fr', 'Signalements d’un seul élément'),
('reports.limitNotice', 'en', 'Showing the newest 500 reports. Use the filters to narrow the list.'),
('reports.limitNotice', 'ru', 'Показаны 500 самых новых сообщений. Сузьте список с помощью фильтров.'),
('reports.limitNotice', 'uz', 'Eng yangi 500 ta xabar ko‘rsatilmoqda. Ro‘yxatni filtrlar bilan toraytiring.'),
('reports.limitNotice', 'fr', 'Affichage des 500 signalements les plus récents. Utilisez les filtres pour affiner la liste.'),
('reports.status.NEW', 'en', 'New'),
('reports.status.NEW', 'ru', 'Новое'),
('reports.status.NEW', 'uz', 'Yangi'),
('reports.status.NEW', 'fr', 'Nouveau'),
('reports.status.IN_REVIEW', 'en', 'In review'),
('reports.status.IN_REVIEW', 'ru', 'На рассмотрении'),
('reports.status.IN_REVIEW', 'uz', 'Ko‘rib chiqilmoqda'),
('reports.status.IN_REVIEW', 'fr', 'En cours d’examen'),
('reports.status.RESOLVED', 'en', 'Resolved'),
('reports.status.RESOLVED', 'ru', 'Решено'),
('reports.status.RESOLVED', 'uz', 'Hal qilindi'),
('reports.status.RESOLVED', 'fr', 'Résolu'),
('reports.status.DISMISSED', 'en', 'Dismissed'),
('reports.status.DISMISSED', 'ru', 'Отклонено'),
('reports.status.DISMISSED', 'uz', 'Rad etildi'),
('reports.status.DISMISSED', 'fr', 'Rejeté'),
('reports.filter.OPEN', 'en', 'Open'),
('reports.filter.OPEN', 'ru', 'Открытые'),
('reports.filter.OPEN', 'uz', 'Ochiq'),
('reports.filter.OPEN', 'fr', 'Ouverts'),
('reports.filter.ALL', 'en', 'All'),
('reports.filter.ALL', 'ru', 'Все'),
('reports.filter.ALL', 'uz', 'Barchasi'),
('reports.filter.ALL', 'fr', 'Tous'),
('reports.startReview', 'en', 'Start review'),
('reports.startReview', 'ru', 'Взять в работу'),
('reports.startReview', 'uz', 'Ko‘rib chiqishni boshlash'),
('reports.startReview', 'fr', 'Commencer l’examen'),
('reports.resolve', 'en', 'Mark resolved'),
('reports.resolve', 'ru', 'Отметить как решённое'),
('reports.resolve', 'uz', 'Hal qilingan deb belgilash'),
('reports.resolve', 'fr', 'Marquer comme résolu'),
('reports.dismiss', 'en', 'Dismiss'),
('reports.dismiss', 'ru', 'Отклонить'),
('reports.dismiss', 'uz', 'Rad etish'),
('reports.dismiss', 'fr', 'Rejeter'),
('reports.markNew', 'en', 'Mark as new'),
('reports.markNew', 'ru', 'Отметить как новое'),
('reports.markNew', 'uz', 'Yangi deb belgilash'),
('reports.markNew', 'fr', 'Marquer comme nouveau'),
('saved.save', 'en', 'Save'),
('saved.save', 'ru', 'Сохранить'),
('saved.save', 'uz', 'Saqlash'),
('saved.save', 'fr', 'Enregistrer'),
('saved.saved', 'en', 'Saved'),
('saved.saved', 'ru', 'Сохранено'),
('saved.saved', 'uz', 'Saqlangan'),
('saved.saved', 'fr', 'Enregistré'),
('saved.remove', 'en', 'Remove from saved'),
('saved.remove', 'ru', 'Убрать из сохранённых'),
('saved.remove', 'uz', 'Saqlanganlardan olib tashlash'),
('saved.remove', 'fr', 'Retirer des enregistrements'),
('saved.removed', 'en', 'Removed from saved services'),
('saved.removed', 'ru', 'Убрано из сохранённых услуг'),
('saved.removed', 'uz', 'Saqlangan xizmatlardan olib tashlandi'),
('saved.removed', 'fr', 'Retiré des services enregistrés'),
('saved.added', 'en', 'Saved in this browser'),
('saved.added', 'ru', 'Сохранено в этом браузере'),
('saved.added', 'uz', 'Ushbu brauzerda saqlandi'),
('saved.added', 'fr', 'Enregistré dans ce navigateur'),
('saved.sessionOnly', 'en', 'Saved for this visit only: this browser blocks local storage.'),
('saved.sessionOnly', 'ru', 'Сохранено только на время этого визита: браузер блокирует локальное хранилище.'),
('saved.sessionOnly', 'uz', 'Faqat ushbu tashrif uchun saqlandi: brauzer mahalliy xotirani bloklaydi.'),
('saved.sessionOnly', 'fr', 'Enregistré pour cette visite uniquement : ce navigateur bloque le stockage local.'),
('saved.full', 'en', 'You can save up to 100 services. Remove some to add more.'),
('saved.full', 'ru', 'Можно сохранить не более 100 услуг. Удалите часть, чтобы добавить новые.'),
('saved.full', 'uz', 'Ko‘pi bilan 100 ta xizmatni saqlash mumkin. Yangilarini qo‘shish uchun ayrimlarini o‘chiring.'),
('saved.full', 'fr', 'Vous pouvez enregistrer jusqu’à 100 services. Retirez-en pour en ajouter d’autres.'),
('saved.title', 'en', 'Saved services'),
('saved.title', 'ru', 'Сохранённые услуги'),
('saved.title', 'uz', 'Saqlangan xizmatlar'),
('saved.title', 'fr', 'Services enregistrés'),
('saved.subtitle', 'en', 'Your list is stored only in this browser. It is not sent to the server and is not linked to you.'),
('saved.subtitle', 'ru', 'Список хранится только в этом браузере. Он не отправляется на сервер и не связан с вами.'),
('saved.subtitle', 'uz', 'Ro‘yxat faqat ushbu brauzerda saqlanadi. U serverga yuborilmaydi va siz bilan bog‘lanmaydi.'),
('saved.subtitle', 'fr', 'Votre liste est conservée uniquement dans ce navigateur. Elle n’est pas envoyée au serveur et n’est pas liée à vous.'),
('saved.printList', 'en', 'Print list'),
('saved.printList', 'ru', 'Распечатать список'),
('saved.printList', 'uz', 'Ro‘yxatni chop etish'),
('saved.printList', 'fr', 'Imprimer la liste'),
('saved.clearAll', 'en', 'Clear all'),
('saved.clearAll', 'ru', 'Очистить всё'),
('saved.clearAll', 'uz', 'Hammasini tozalash'),
('saved.clearAll', 'fr', 'Tout effacer'),
('saved.clearConfirm', 'en', 'Remove every saved service from this browser?'),
('saved.clearConfirm', 'ru', 'Удалить все сохранённые услуги из этого браузера?'),
('saved.clearConfirm', 'uz', 'Barcha saqlangan xizmatlar ushbu brauzerdan o‘chirilsinmi?'),
('saved.clearConfirm', 'fr', 'Retirer tous les services enregistrés de ce navigateur ?'),
('saved.cleared', 'en', 'Saved services cleared'),
('saved.cleared', 'ru', 'Сохранённые услуги очищены'),
('saved.cleared', 'uz', 'Saqlangan xizmatlar tozalandi'),
('saved.cleared', 'fr', 'Services enregistrés effacés'),
('saved.emptyTitle', 'en', 'You have not saved any services yet'),
('saved.emptyTitle', 'ru', 'Вы пока ничего не сохранили'),
('saved.emptyTitle', 'uz', 'Siz hali hech qanday xizmatni saqlamadingiz'),
('saved.emptyTitle', 'fr', 'Vous n’avez encore enregistré aucun service'),
('saved.emptyText', 'en', 'Use the Save button on a service to keep it here for later.'),
('saved.emptyText', 'ru', 'Нажмите «Сохранить» на странице услуги, чтобы вернуться к ней позже.'),
('saved.emptyText', 'uz', 'Xizmatni keyinroq ko‘rish uchun undagi «Saqlash» tugmasini bosing.'),
('saved.emptyText', 'fr', 'Utilisez le bouton Enregistrer d’un service pour le retrouver ici plus tard.'),
('saved.unavailable', 'en', 'No longer published'),
('saved.unavailable', 'ru', 'Больше не опубликовано'),
('saved.unavailable', 'uz', 'Endi e’lon qilinmagan'),
('saved.unavailable', 'fr', 'N’est plus publié'),
('saved.savedOn', 'en', 'Saved on'),
('saved.savedOn', 'ru', 'Сохранено'),
('saved.savedOn', 'uz', 'Saqlangan sana'),
('saved.savedOn', 'fr', 'Enregistré le'),
('share.action', 'en', 'Share'),
('share.action', 'ru', 'Поделиться'),
('share.action', 'uz', 'Ulashish'),
('share.action', 'fr', 'Partager'),
('share.copied', 'en', 'Link copied to the clipboard'),
('share.copied', 'ru', 'Ссылка скопирована в буфер обмена'),
('share.copied', 'uz', 'Havola buferga nusxalandi'),
('share.copied', 'fr', 'Lien copié dans le presse-papiers'),
('share.manualTitle', 'en', 'Copy the link'),
('share.manualTitle', 'ru', 'Скопируйте ссылку'),
('share.manualTitle', 'uz', 'Havoladan nusxa oling'),
('share.manualTitle', 'fr', 'Copiez le lien'),
('share.manualHint', 'en', 'Your browser does not allow automatic copying. Select the link and copy it.'),
('share.manualHint', 'ru', 'Браузер не разрешает автоматическое копирование. Выделите ссылку и скопируйте её.'),
('share.manualHint', 'uz', 'Brauzeringiz avtomatik nusxalashga ruxsat bermaydi. Havolani belgilab, nusxa oling.'),
('share.manualHint', 'fr', 'Votre navigateur n’autorise pas la copie automatique. Sélectionnez le lien et copiez-le.'),
('share.link', 'en', 'Link'),
('share.link', 'ru', 'Ссылка'),
('share.link', 'uz', 'Havola'),
('share.link', 'fr', 'Lien'),
('validation.url', 'en', 'Enter a full link that starts with https://'),
('validation.url', 'ru', 'Укажите полную ссылку, начинающуюся с https://'),
('validation.url', 'uz', 'https:// bilan boshlanadigan to‘liq havolani kiriting'),
('validation.url', 'fr', 'Saisissez un lien complet commençant par https://'),
('validation.tooManyItems', 'en', 'Use at most 50 lines'),
('validation.tooManyItems', 'ru', 'Не более 50 строк'),
('validation.tooManyItems', 'uz', 'Ko‘pi bilan 50 qator'),
('validation.tooManyItems', 'fr', '50 lignes au maximum'),
('validation.phone', 'en', 'Use digits, spaces, brackets, hyphens and an optional leading +'),
('validation.phone', 'ru', 'Используйте цифры, пробелы, скобки, дефисы и при необходимости + в начале'),
('validation.phone', 'uz', 'Raqamlar, bo‘shliqlar, qavslar, chiziqchalar va boshida ixtiyoriy + belgisidan foydalaning'),
('validation.phone', 'fr', 'Utilisez des chiffres, espaces, parenthèses, tirets et éventuellement un + au début'),
('validation.latitude', 'en', 'Latitude must be between -90 and 90'),
('validation.latitude', 'ru', 'Широта должна быть от -90 до 90'),
('validation.latitude', 'uz', 'Kenglik -90 va 90 oralig‘ida bo‘lishi kerak'),
('validation.latitude', 'fr', 'La latitude doit être comprise entre -90 et 90'),
('validation.longitude', 'en', 'Longitude must be between -180 and 180'),
('validation.longitude', 'ru', 'Долгота должна быть от -180 до 180'),
('validation.longitude', 'uz', 'Uzunlik -180 va 180 oralig‘ida bo‘lishi kerak'),
('validation.longitude', 'fr', 'La longitude doit être comprise entre -180 et 180'),
('validation.coordinatesPair', 'en', 'Enter both latitude and longitude, or leave both empty'),
('validation.coordinatesPair', 'ru', 'Укажите и широту, и долготу либо оставьте оба поля пустыми'),
('validation.coordinatesPair', 'uz', 'Kenglik va uzunlikni birga kiriting yoki ikkalasini ham bo‘sh qoldiring'),
('validation.coordinatesPair', 'fr', 'Saisissez la latitude et la longitude, ou laissez les deux vides'),
('verification.title', 'en', 'Information check'),
('verification.title', 'ru', 'Проверка информации'),
('verification.title', 'uz', 'Ma’lumotlar tekshiruvi'),
('verification.title', 'fr', 'Vérification des informations'),
('verification.column', 'en', 'Verification'),
('verification.column', 'ru', 'Проверка'),
('verification.column', 'uz', 'Tekshiruv'),
('verification.column', 'fr', 'Vérification'),
('verification.status.UNVERIFIED', 'en', 'Not verified'),
('verification.status.UNVERIFIED', 'ru', 'Не проверено'),
('verification.status.UNVERIFIED', 'uz', 'Tekshirilmagan'),
('verification.status.UNVERIFIED', 'fr', 'Non vérifié'),
('verification.status.VERIFIED', 'en', 'Verified'),
('verification.status.VERIFIED', 'ru', 'Проверено'),
('verification.status.VERIFIED', 'uz', 'Tekshirilgan'),
('verification.status.VERIFIED', 'fr', 'Vérifié'),
('verification.status.DUE', 'en', 'Recheck due'),
('verification.status.DUE', 'ru', 'Пора перепроверить'),
('verification.status.DUE', 'uz', 'Qayta tekshirish vaqti'),
('verification.status.DUE', 'fr', 'Revérification à faire'),
('verification.status.OUTDATED', 'en', 'Changed since verification'),
('verification.status.OUTDATED', 'ru', 'Изменено после проверки'),
('verification.status.OUTDATED', 'uz', 'Tekshiruvdan keyin o‘zgargan'),
('verification.status.OUTDATED', 'fr', 'Modifié depuis la vérification'),
('verification.filterDue', 'en', 'Needs recheck'),
('verification.filterDue', 'ru', 'Требует проверки'),
('verification.filterDue', 'uz', 'Tekshirish kerak'),
('verification.filterDue', 'fr', 'À revérifier'),
('verification.verify', 'en', 'Mark as verified'),
('verification.verify', 'ru', 'Отметить как проверенное'),
('verification.verify', 'uz', 'Tekshirilgan deb belgilash'),
('verification.verify', 'fr', 'Marquer comme vérifié'),
('verification.done', 'en', 'Marked as verified'),
('verification.done', 'ru', 'Отмечено как проверенное'),
('verification.done', 'uz', 'Tekshirilgan deb belgilandi'),
('verification.done', 'fr', 'Marqué comme vérifié'),
('verification.lastVerified', 'en', 'Last verified'),
('verification.lastVerified', 'ru', 'Последняя проверка'),
('verification.lastVerified', 'uz', 'Oxirgi tekshiruv'),
('verification.lastVerified', 'fr', 'Dernière vérification'),
('verification.verifiedBy', 'en', 'Verified by'),
('verification.verifiedBy', 'ru', 'Проверил(а)'),
('verification.verifiedBy', 'uz', 'Tekshirgan'),
('verification.verifiedBy', 'fr', 'Vérifié par'),
('verification.byYou', 'en', 'you'),
('verification.byYou', 'ru', 'вы'),
('verification.byYou', 'uz', 'siz'),
('verification.byYou', 'fr', 'vous'),
('verification.officialSource', 'en', 'Official source'),
('verification.officialSource', 'ru', 'Официальный источник'),
('verification.officialSource', 'uz', 'Rasmiy manba'),
('verification.officialSource', 'fr', 'Source officielle'),
('verification.officialSourceUrl', 'en', 'Official source link'),
('verification.officialSourceUrl', 'ru', 'Ссылка на официальный источник'),
('verification.officialSourceUrl', 'uz', 'Rasmiy manba havolasi'),
('verification.officialSourceUrl', 'fr', 'Lien vers la source officielle'),
('verification.officialSourceHint', 'en', 'Link to the government page that confirms this information. Required before verification.'),
('verification.officialSourceHint', 'ru', 'Ссылка на государственную страницу, подтверждающую эти сведения. Нужна для проверки.'),
('verification.officialSourceHint', 'uz', 'Ushbu ma’lumotni tasdiqlovchi davlat sahifasiga havola. Tekshiruvdan oldin talab qilinadi.'),
('verification.officialSourceHint', 'fr', 'Lien vers la page officielle qui confirme ces informations. Obligatoire avant la vérification.'),
('verification.noSource', 'en', 'Not added yet'),
('verification.noSource', 'ru', 'Пока не добавлена'),
('verification.noSource', 'uz', 'Hali qo‘shilmagan'),
('verification.noSource', 'fr', 'Pas encore ajouté'),
('verification.sourceRequired', 'en', 'Add the official source link before verifying.'),
('verification.sourceRequired', 'ru', 'Перед проверкой добавьте ссылку на официальный источник.'),
('verification.sourceRequired', 'uz', 'Tekshirishdan oldin rasmiy manba havolasini qo‘shing.'),
('verification.sourceRequired', 'fr', 'Ajoutez le lien vers la source officielle avant de vérifier.'),
('verification.hintUnverified', 'en', 'Compare every field with the official source, then mark the service as verified.'),
('verification.hintUnverified', 'ru', 'Сверьте каждое поле с официальным источником, затем отметьте услугу как проверенную.'),
('verification.hintUnverified', 'uz', 'Har bir maydonni rasmiy manba bilan solishtiring, so‘ng xizmatni tekshirilgan deb belgilang.'),
('verification.hintUnverified', 'fr', 'Comparez chaque champ à la source officielle, puis marquez le service comme vérifié.'),
('verification.hintVerified', 'en', 'Editing key fields will mark this verification as outdated.'),
('verification.hintVerified', 'ru', 'Изменение ключевых полей сделает эту проверку устаревшей.'),
('verification.hintVerified', 'uz', 'Asosiy maydonlar o‘zgartirilsa, bu tekshiruv eskirgan deb belgilanadi.'),
('verification.hintVerified', 'fr', 'Modifier des champs clés rendra cette vérification obsolète.'),
('verification.hintDue', 'en', 'The last check is older than 180 days. Recheck the official source.'),
('verification.hintDue', 'ru', 'Последней проверке больше 180 дней. Сверьтесь с официальным источником ещё раз.'),
('verification.hintDue', 'uz', 'Oxirgi tekshiruvdan 180 kundan ko‘proq vaqt o‘tgan. Rasmiy manbani qayta tekshiring.'),
('verification.hintDue', 'fr', 'La dernière vérification date de plus de 180 jours. Revérifiez la source officielle.'),
('verification.hintOutdated', 'en', 'Key fields changed after the last check. Recheck before relying on this information.'),
('verification.hintOutdated', 'ru', 'Ключевые поля изменились после последней проверки. Перепроверьте, прежде чем полагаться на эти сведения.'),
('verification.hintOutdated', 'uz', 'Oxirgi tekshiruvdan keyin asosiy maydonlar o‘zgargan. Ushbu ma’lumotga tayanishdan oldin qayta tekshiring.'),
('verification.hintOutdated', 'fr', 'Des champs clés ont changé depuis la dernière vérification. Revérifiez avant de vous fier à ces informations.'),
('verification.verifiedOn', 'en', 'Checked against the official source on'),
('verification.verifiedOn', 'ru', 'Сверено с официальным источником'),
('verification.verifiedOn', 'uz', 'Rasmiy manba bilan solishtirilgan sana:'),
('verification.verifiedOn', 'fr', 'Vérifié auprès de la source officielle le'),
('verification.outdatedPublic', 'en', 'This information changed after its last check. A new check against the official source is pending.'),
('verification.outdatedPublic', 'ru', 'Эти сведения изменились после последней проверки. Новая сверка с официальным источником ещё не проведена.'),
('verification.outdatedPublic', 'uz', 'Ushbu ma’lumot oxirgi tekshiruvdan keyin o‘zgargan. Rasmiy manba bilan yangi tekshiruv hali o‘tkazilmagan.'),
('verification.outdatedPublic', 'fr', 'Ces informations ont changé depuis leur dernière vérification. Une nouvelle vérification auprès de la source officielle est en attente.'),
('verification.unverifiedPublic', 'en', 'This information has not yet been checked against an official source.'),
('verification.unverifiedPublic', 'ru', 'Эти сведения ещё не сверены с официальным источником.'),
('verification.unverifiedPublic', 'uz', 'Ushbu ma’lumot hali rasmiy manba bilan solishtirilmagan.'),
('verification.unverifiedPublic', 'fr', 'Ces informations n’ont pas encore été vérifiées auprès d’une source officielle.'),
('verification.openReports', 'en', 'Open reports'),
('verification.openReports', 'ru', 'Открытые сообщения'),
('verification.openReports', 'uz', 'Ochiq xabarlar'),
('verification.openReports', 'fr', 'Signalements ouverts'),
('verification.dashboardServices', 'en', 'Services to verify'),
('verification.dashboardServices', 'ru', 'Услуги на проверку'),
('verification.dashboardServices', 'uz', 'Tekshiriladigan xizmatlar'),
('verification.dashboardServices', 'fr', 'Services à vérifier'),
('verification.dashboardServicesHint', 'en', 'Published, need a check'),
('verification.dashboardServicesHint', 'ru', 'Опубликованы, нужна проверка'),
('verification.dashboardServicesHint', 'uz', 'E’lon qilingan, tekshiruv kerak'),
('verification.dashboardServicesHint', 'fr', 'Publiés, à vérifier'),
('verification.dashboardOrganizations', 'en', 'Organizations to verify'),
('verification.dashboardOrganizations', 'ru', 'Организации на проверку'),
('verification.dashboardOrganizations', 'uz', 'Tekshiriladigan tashkilotlar'),
('verification.dashboardOrganizations', 'fr', 'Organisations à vérifier'),
('verification.dashboardOrganizationsHint', 'en', 'Active, need a check'),
('verification.dashboardOrganizationsHint', 'ru', 'Активны, нужна проверка'),
('verification.dashboardOrganizationsHint', 'uz', 'Faol, tekshiruv kerak'),
('verification.dashboardOrganizationsHint', 'fr', 'Actives, à vérifier');
INSERT INTO translation_keys (translation_key, required, active)
SELECT DISTINCT key, TRUE, TRUE FROM public_catalog_labels ON CONFLICT (translation_key) DO NOTHING;
INSERT INTO translations (translation_key_id, language_code, translation_value)
SELECT k.id, s.lang, s.value FROM public_catalog_labels s JOIN translation_keys k ON k.translation_key = s.key
ON CONFLICT (language_code, translation_key_id) DO NOTHING;
