CREATE TEMPORARY TABLE organization_analytics_labels (key VARCHAR(150), lang VARCHAR(64), value TEXT) ON COMMIT DROP;
INSERT INTO organization_analytics_labels VALUES
('nav.orgDashboard', 'en', 'Organization dashboard'),
('nav.orgDashboard', 'ru', 'Панель организации'),
('nav.orgDashboard', 'uz', 'Tashkilot paneli'),
('nav.orgDashboard', 'fr', 'Tableau de bord de l’organisation'),
('analytics.title', 'en', 'Organization dashboard'),
('analytics.title', 'ru', 'Панель организации'),
('analytics.title', 'uz', 'Tashkilot paneli'),
('analytics.title', 'fr', 'Tableau de bord de l’organisation'),
('analytics.subtitle', 'en', 'Service card status, quality issues, visitor reports and interest in your catalog information.'),
('analytics.subtitle', 'ru', 'Состояние карточек услуг, проблемы качества, сообщения посетителей и интерес к информации в каталоге.'),
('analytics.subtitle', 'uz', 'Xizmat kartalari holati, sifat muammolari, tashrifchilar xabarlari va katalogdagi ma’lumotlarga qiziqish.'),
('analytics.subtitle', 'fr', 'État des fiches de services, problèmes de qualité, signalements des visiteurs et intérêt pour les informations du catalogue.'),
('analytics.allOrganizations', 'en', 'All organizations'),
('analytics.allOrganizations', 'ru', 'Все организации'),
('analytics.allOrganizations', 'uz', 'Barcha tashkilotlar'),
('analytics.allOrganizations', 'fr', 'Toutes les organisations'),
('analytics.allMyOrganizations', 'en', 'All my organizations'),
('analytics.allMyOrganizations', 'ru', 'Все мои организации'),
('analytics.allMyOrganizations', 'uz', 'Barcha tashkilotlarim'),
('analytics.allMyOrganizations', 'fr', 'Toutes mes organisations'),
('analytics.allCategories', 'en', 'All categories'),
('analytics.allCategories', 'ru', 'Все категории'),
('analytics.allCategories', 'uz', 'Barcha toifalar'),
('analytics.allCategories', 'fr', 'Toutes les catégories'),
('analytics.category', 'en', 'Service category'),
('analytics.category', 'ru', 'Категория услуг'),
('analytics.category', 'uz', 'Xizmat toifasi'),
('analytics.category', 'fr', 'Catégorie de service'),
('analytics.period', 'en', 'Period'),
('analytics.period', 'ru', 'Период'),
('analytics.period', 'uz', 'Davr'),
('analytics.period', 'fr', 'Période'),
('analytics.preset.7', 'en', 'Last 7 days'),
('analytics.preset.7', 'ru', 'Последние 7 дней'),
('analytics.preset.7', 'uz', 'Oxirgi 7 kun'),
('analytics.preset.7', 'fr', '7 derniers jours'),
('analytics.preset.30', 'en', 'Last 30 days'),
('analytics.preset.30', 'ru', 'Последние 30 дней'),
('analytics.preset.30', 'uz', 'Oxirgi 30 kun'),
('analytics.preset.30', 'fr', '30 derniers jours'),
('analytics.preset.90', 'en', 'Last 90 days'),
('analytics.preset.90', 'ru', 'Последние 90 дней'),
('analytics.preset.90', 'uz', 'Oxirgi 90 kun'),
('analytics.preset.90', 'fr', '90 derniers jours'),
('analytics.preset.365', 'en', 'Last 365 days'),
('analytics.preset.365', 'ru', 'Последние 365 дней'),
('analytics.preset.365', 'uz', 'Oxirgi 365 kun'),
('analytics.preset.365', 'fr', '365 derniers jours'),
('analytics.customPeriod', 'en', 'Custom period'),
('analytics.customPeriod', 'ru', 'Свой период'),
('analytics.customPeriod', 'uz', 'Boshqa davr'),
('analytics.customPeriod', 'fr', 'Période personnalisée'),
('analytics.from', 'en', 'From'),
('analytics.from', 'ru', 'С'),
('analytics.from', 'uz', 'Boshlanishi'),
('analytics.from', 'fr', 'Du'),
('analytics.to', 'en', 'To'),
('analytics.to', 'ru', 'По'),
('analytics.to', 'uz', 'Tugashi'),
('analytics.to', 'fr', 'Au'),
('analytics.filterScope', 'en', 'Status counts, quality issues and unresolved reports show the current state. The period applies to catalog engagement and to reports received.'),
('analytics.filterScope', 'ru', 'Число карточек по статусам, проблемы качества и нерешённые сообщения показывают текущее состояние. Период применяется к активности в каталоге и к полученным сообщениям.'),
('analytics.filterScope', 'uz', 'Holatlar bo‘yicha sonlar, sifat muammolari va hal qilinmagan xabarlar joriy holatni ko‘rsatadi. Davr katalogdagi faollik va kelib tushgan xabarlarga qo‘llaniladi.'),
('analytics.filterScope', 'fr', 'Les nombres par statut, les problèmes de qualité et les signalements non résolus montrent l’état actuel. La période s’applique à l’activité du catalogue et aux signalements reçus.'),
('analytics.timeZone', 'en', 'Tashkent time'),
('analytics.timeZone', 'ru', 'время Ташкента'),
('analytics.timeZone', 'uz', 'Toshkent vaqti'),
('analytics.timeZone', 'fr', 'heure de Tachkent'),
('analytics.rangeOrder', 'en', 'The start date must not be after the end date'),
('analytics.rangeOrder', 'ru', 'Дата начала не может быть позже даты окончания'),
('analytics.rangeOrder', 'uz', 'Boshlanish sanasi tugash sanasidan keyin bo‘lmasligi kerak'),
('analytics.rangeOrder', 'fr', 'La date de début ne doit pas être postérieure à la date de fin'),
('analytics.rangeTooLong', 'en', 'Choose a period of at most 366 days'),
('analytics.rangeTooLong', 'ru', 'Выберите период не длиннее 366 дней'),
('analytics.rangeTooLong', 'uz', 'Davr 366 kundan oshmasligi kerak'),
('analytics.rangeTooLong', 'fr', 'Choisissez une période de 366 jours au maximum'),
('analytics.disclaimer', 'en', 'Engagement figures count anonymous views and link clicks on this information site. They are not applications, customers or completed services, and staff visits are not counted.'),
('analytics.disclaimer', 'ru', 'Показатели активности — это анонимные просмотры и переходы по ссылкам на этом информационном сайте. Это не заявления, не клиенты и не оказанные услуги; посещения сотрудников не учитываются.'),
('analytics.disclaimer', 'uz', 'Faollik ko‘rsatkichlari ushbu axborot saytidagi anonim ko‘rishlar va havolalarni bosishlarni sanaydi. Ular ariza, mijoz yoki ko‘rsatilgan xizmat emas, xodimlarning tashriflari hisobga olinmaydi.'),
('analytics.disclaimer', 'fr', 'Les indicateurs d’activité comptent les consultations et clics anonymes sur ce site d’information. Ce ne sont ni des demandes, ni des usagers, ni des services rendus, et les visites du personnel ne sont pas comptées.'),
('analytics.snapshotTitle', 'en', 'Service cards now'),
('analytics.snapshotTitle', 'ru', 'Карточки услуг сейчас'),
('analytics.snapshotTitle', 'uz', 'Xizmat kartalari hozir'),
('analytics.snapshotTitle', 'fr', 'Fiches de services actuellement'),
('analytics.currentState', 'en', 'Current state'),
('analytics.currentState', 'ru', 'Текущее состояние'),
('analytics.currentState', 'uz', 'Joriy holat'),
('analytics.currentState', 'fr', 'État actuel'),
('analytics.attentionTitle', 'en', 'Needs attention'),
('analytics.attentionTitle', 'ru', 'Требует внимания'),
('analytics.attentionTitle', 'uz', 'E’tibor talab qiladi'),
('analytics.attentionTitle', 'fr', 'À traiter'),
('analytics.cardsWithIssues', 'en', 'Cards with at least one issue:'),
('analytics.cardsWithIssues', 'ru', 'Карточек хотя бы с одной проблемой:'),
('analytics.cardsWithIssues', 'uz', 'Kamida bitta muammosi bor kartalar:'),
('analytics.cardsWithIssues', 'fr', 'Fiches avec au moins un problème :'),
('analytics.showInQueue', 'en', 'Show these cards in the queue'),
('analytics.showInQueue', 'ru', 'Показать эти карточки в очереди'),
('analytics.showInQueue', 'uz', 'Bu kartalarni navbatda ko‘rsatish'),
('analytics.showInQueue', 'fr', 'Afficher ces fiches dans la file'),
('analytics.engagementTitle', 'en', 'Catalog engagement'),
('analytics.engagementTitle', 'ru', 'Активность в каталоге'),
('analytics.engagementTitle', 'uz', 'Katalogdagi faollik'),
('analytics.engagementTitle', 'fr', 'Activité du catalogue'),
('analytics.previousPeriod', 'en', 'Previous period:'),
('analytics.previousPeriod', 'ru', 'Предыдущий период:'),
('analytics.previousPeriod', 'uz', 'Oldingi davr:'),
('analytics.previousPeriod', 'fr', 'Période précédente :'),
('analytics.exportServices', 'en', 'Services CSV'),
('analytics.exportServices', 'ru', 'CSV по услугам'),
('analytics.exportServices', 'uz', 'Xizmatlar CSV'),
('analytics.exportServices', 'fr', 'CSV par service'),
('analytics.exportDaily', 'en', 'Daily CSV'),
('analytics.exportDaily', 'ru', 'CSV по дням'),
('analytics.exportDaily', 'uz', 'Kunlik CSV'),
('analytics.exportDaily', 'fr', 'CSV par jour'),
('analytics.event.CATALOG_VIEW', 'en', 'Catalog page views'),
('analytics.event.CATALOG_VIEW', 'ru', 'Просмотры страниц каталога'),
('analytics.event.CATALOG_VIEW', 'uz', 'Katalog sahifalari ko‘rishlari'),
('analytics.event.CATALOG_VIEW', 'fr', 'Consultations des pages du catalogue'),
('analytics.event.SERVICE_VIEW', 'en', 'Service page views'),
('analytics.event.SERVICE_VIEW', 'ru', 'Просмотры страниц услуг'),
('analytics.event.SERVICE_VIEW', 'uz', 'Xizmat sahifalari ko‘rishlari'),
('analytics.event.SERVICE_VIEW', 'fr', 'Consultations des pages de service'),
('analytics.event.OFFICIAL_LINK_CLICK', 'en', 'Official website clicks'),
('analytics.event.OFFICIAL_LINK_CLICK', 'ru', 'Переходы на официальный сайт'),
('analytics.event.OFFICIAL_LINK_CLICK', 'uz', 'Rasmiy saytga o‘tishlar'),
('analytics.event.OFFICIAL_LINK_CLICK', 'fr', 'Clics vers le site officiel'),
('analytics.event.PHONE_CLICK', 'en', 'Phone link clicks'),
('analytics.event.PHONE_CLICK', 'ru', 'Нажатия на телефон'),
('analytics.event.PHONE_CLICK', 'uz', 'Telefon havolasini bosishlar'),
('analytics.event.PHONE_CLICK', 'fr', 'Clics sur le téléphone'),
('analytics.event.MAP_CLICK', 'en', 'Map link clicks'),
('analytics.event.MAP_CLICK', 'ru', 'Переходы на карту'),
('analytics.event.MAP_CLICK', 'uz', 'Xarita havolasini bosishlar'),
('analytics.event.MAP_CLICK', 'fr', 'Clics vers la carte'),
('analytics.event.PRINT', 'en', 'Prints'),
('analytics.event.PRINT', 'ru', 'Печать'),
('analytics.event.PRINT', 'uz', 'Chop etishlar'),
('analytics.event.PRINT', 'fr', 'Impressions'),
('analytics.linkClicks', 'en', 'Link clicks'),
('analytics.linkClicks', 'ru', 'Переходы по ссылкам'),
('analytics.linkClicks', 'uz', 'Havolalarni bosishlar'),
('analytics.linkClicks', 'fr', 'Clics sur les liens'),
('analytics.vsPrevious', 'en', 'vs previous period'),
('analytics.vsPrevious', 'ru', 'к предыдущему периоду'),
('analytics.vsPrevious', 'uz', 'oldingi davrga nisbatan'),
('analytics.vsPrevious', 'fr', 'par rapport à la période précédente'),
('analytics.noPreviousActivity', 'en', 'None in the previous period'),
('analytics.noPreviousActivity', 'ru', 'В предыдущем периоде не было'),
('analytics.noPreviousActivity', 'uz', 'Oldingi davrda bo‘lmagan'),
('analytics.noPreviousActivity', 'fr', 'Aucune sur la période précédente'),
('analytics.noActivityBoth', 'en', 'No activity in either period'),
('analytics.noActivityBoth', 'ru', 'Нет активности ни в одном периоде'),
('analytics.noActivityBoth', 'uz', 'Ikkala davrda ham faollik yo‘q'),
('analytics.noActivityBoth', 'fr', 'Aucune activité sur les deux périodes'),
('analytics.dailyTrend', 'en', 'Daily trend'),
('analytics.dailyTrend', 'ru', 'Динамика по дням'),
('analytics.dailyTrend', 'uz', 'Kunlik dinamika'),
('analytics.dailyTrend', 'fr', 'Évolution quotidienne'),
('analytics.weeklyTrend', 'en', 'Weekly trend'),
('analytics.weeklyTrend', 'ru', 'Динамика по неделям'),
('analytics.weeklyTrend', 'uz', 'Haftalik dinamika'),
('analytics.weeklyTrend', 'fr', 'Évolution hebdomadaire'),
('analytics.metric', 'en', 'Metric'),
('analytics.metric', 'ru', 'Показатель'),
('analytics.metric', 'uz', 'Ko‘rsatkich'),
('analytics.metric', 'fr', 'Indicateur'),
('analytics.showTable', 'en', 'Show table'),
('analytics.showTable', 'ru', 'Показать таблицу'),
('analytics.showTable', 'uz', 'Jadvalni ko‘rsatish'),
('analytics.showTable', 'fr', 'Afficher le tableau'),
('analytics.showChart', 'en', 'Show chart'),
('analytics.showChart', 'ru', 'Показать график'),
('analytics.showChart', 'uz', 'Grafikni ko‘rsatish'),
('analytics.showChart', 'fr', 'Afficher le graphique'),
('analytics.chartHint', 'en', 'Use the arrow keys to move between bars.'),
('analytics.chartHint', 'ru', 'Перемещайтесь между столбцами клавишами со стрелками.'),
('analytics.chartHint', 'uz', 'Ustunlar orasida strelka tugmalari bilan o‘ting.'),
('analytics.chartHint', 'fr', 'Utilisez les flèches pour passer d’une barre à l’autre.'),
('analytics.noActivity', 'en', 'No activity recorded in this period'),
('analytics.noActivity', 'ru', 'За этот период активность не зафиксирована'),
('analytics.noActivity', 'uz', 'Bu davrda faollik qayd etilmagan'),
('analytics.noActivity', 'fr', 'Aucune activité enregistrée sur cette période'),
('analytics.total', 'en', 'Total'),
('analytics.total', 'ru', 'Всего'),
('analytics.total', 'uz', 'Jami'),
('analytics.total', 'fr', 'Total'),
('analytics.mostViewed', 'en', 'Most viewed services'),
('analytics.mostViewed', 'ru', 'Самые просматриваемые услуги'),
('analytics.mostViewed', 'uz', 'Eng ko‘p ko‘rilgan xizmatlar'),
('analytics.mostViewed', 'fr', 'Services les plus consultés'),
('analytics.noViewsTitle', 'en', 'No service page views in this period'),
('analytics.noViewsTitle', 'ru', 'За этот период страницы услуг не просматривались'),
('analytics.noViewsTitle', 'uz', 'Bu davrda xizmat sahifalari ko‘rilmagan'),
('analytics.noViewsTitle', 'fr', 'Aucune consultation de page de service sur cette période'),
('analytics.noViewsText', 'en', 'Views appear here after visitors open published service pages.'),
('analytics.noViewsText', 'ru', 'Просмотры появятся здесь, когда посетители откроют опубликованные страницы услуг.'),
('analytics.noViewsText', 'uz', 'Tashrifchilar e’lon qilingan xizmat sahifalarini ochgach, ko‘rishlar shu yerda chiqadi.'),
('analytics.noViewsText', 'fr', 'Les consultations apparaissent ici lorsque des visiteurs ouvrent des pages de services publiées.'),
('analytics.views', 'en', 'Views:'),
('analytics.views', 'ru', 'Просмотры:'),
('analytics.views', 'uz', 'Ko‘rishlar:'),
('analytics.views', 'fr', 'Consultations :'),
('analytics.actions', 'en', 'Link clicks and prints:'),
('analytics.actions', 'ru', 'Переходы и печать:'),
('analytics.actions', 'uz', 'Havolalar va chop etish:'),
('analytics.actions', 'fr', 'Clics et impressions :'),
('export.csv', 'en', 'Export CSV'),
('export.csv', 'ru', 'Экспорт в CSV'),
('export.csv', 'uz', 'CSV eksport'),
('export.csv', 'fr', 'Exporter en CSV'),
('export.ready', 'en', 'Downloaded:'),
('export.ready', 'ru', 'Скачано:'),
('export.ready', 'uz', 'Yuklab olindi:'),
('export.ready', 'fr', 'Téléchargé :'),
('export.truncated', 'en', 'The export contains the first 10,000 rows. Narrow the filters to export the rest.'),
('export.truncated', 'ru', 'Экспорт содержит первые 10 000 строк. Сузьте фильтры, чтобы выгрузить остальные.'),
('export.truncated', 'uz', 'Eksportda dastlabki 10 000 qator bor. Qolganlarini olish uchun filtrlarni toraytiring.'),
('export.truncated', 'fr', 'L’export contient les 10 000 premières lignes. Affinez les filtres pour exporter le reste.'),
('quality.title', 'en', 'Service cards that need attention'),
('quality.title', 'ru', 'Карточки услуг, требующие внимания'),
('quality.title', 'uz', 'E’tibor talab qiladigan xizmat kartalari'),
('quality.title', 'fr', 'Fiches de services à traiter'),
('quality.subtitle', 'en', 'Current state of non-deactivated cards. Fixing a card removes it from the queue on the next load.'),
('quality.subtitle', 'ru', 'Текущее состояние неотключённых карточек. Исправленная карточка исчезнет из очереди при следующей загрузке.'),
('quality.subtitle', 'uz', 'O‘chirilmagan kartalarning joriy holati. Tuzatilgan karta keyingi yuklashda navbatdan chiqadi.'),
('quality.subtitle', 'fr', 'État actuel des fiches non désactivées. Une fiche corrigée quitte la file au prochain chargement.'),
('quality.issueFilter', 'en', 'Issue'),
('quality.issueFilter', 'ru', 'Проблема'),
('quality.issueFilter', 'uz', 'Muammo'),
('quality.issueFilter', 'fr', 'Problème'),
('quality.allIssues', 'en', 'All issues'),
('quality.allIssues', 'ru', 'Все проблемы'),
('quality.allIssues', 'uz', 'Barcha muammolar'),
('quality.allIssues', 'fr', 'Tous les problèmes'),
('quality.whatToFix', 'en', 'What to fix'),
('quality.whatToFix', 'ru', 'Что исправить'),
('quality.whatToFix', 'uz', 'Nimani tuzatish kerak'),
('quality.whatToFix', 'fr', 'À corriger'),
('quality.fixInEditor', 'en', 'Fix in editor'),
('quality.fixInEditor', 'ru', 'Исправить в редакторе'),
('quality.fixInEditor', 'uz', 'Muharrirda tuzatish'),
('quality.fixInEditor', 'fr', 'Corriger dans l’éditeur'),
('quality.lastVerified', 'en', 'Last verified:'),
('quality.lastVerified', 'ru', 'Последняя проверка:'),
('quality.lastVerified', 'uz', 'Oxirgi tekshiruv:'),
('quality.lastVerified', 'fr', 'Dernière vérification :'),
('quality.editorAccessNeeded', 'en', 'Changing the card requires service editor access.'),
('quality.editorAccessNeeded', 'ru', 'Для изменения карточки нужен доступ редактора услуг.'),
('quality.editorAccessNeeded', 'uz', 'Kartani o‘zgartirish uchun xizmat muharriri huquqi kerak.'),
('quality.editorAccessNeeded', 'fr', 'La modification de la fiche nécessite un accès éditeur.'),
('quality.languagesUnavailable', 'en', 'Translation gaps could not be checked because the list of active languages is unavailable. Other checks are complete.'),
('quality.languagesUnavailable', 'ru', 'Пробелы в переводах не проверены: список активных языков недоступен. Остальные проверки выполнены.'),
('quality.languagesUnavailable', 'uz', 'Faol tillar ro‘yxati mavjud emasligi sababli tarjimalar tekshirilmadi. Boshqa tekshiruvlar bajarildi.'),
('quality.languagesUnavailable', 'fr', 'Les traductions manquantes n’ont pas pu être vérifiées car la liste des langues actives est indisponible. Les autres contrôles sont faits.'),
('quality.languagesUnknown', 'en', 'Language list unavailable'),
('quality.languagesUnknown', 'ru', 'Список языков недоступен'),
('quality.languagesUnknown', 'uz', 'Tillar ro‘yxati mavjud emas'),
('quality.languagesUnknown', 'fr', 'Liste des langues indisponible'),
('quality.emptyTitle', 'en', 'No cards need attention'),
('quality.emptyTitle', 'ru', 'Нет карточек, требующих внимания'),
('quality.emptyTitle', 'uz', 'E’tibor talab qiladigan kartalar yo‘q'),
('quality.emptyTitle', 'fr', 'Aucune fiche à traiter'),
('quality.emptyText', 'en', 'Every card in this view has a current verification, an official source, the required fields and all translations.'),
('quality.emptyText', 'ru', 'У всех карточек в этом списке актуальная проверка, официальный источник, обязательные поля и все переводы.'),
('quality.emptyText', 'uz', 'Bu ro‘yxatdagi barcha kartalarda dolzarb tekshiruv, rasmiy manba, majburiy maydonlar va barcha tarjimalar bor.'),
('quality.emptyText', 'fr', 'Toutes les fiches affichées ont une vérification à jour, une source officielle, les champs obligatoires et toutes les traductions.'),
('quality.issue.VERIFICATION_OVERDUE', 'en', 'Verification overdue'),
('quality.issue.VERIFICATION_OVERDUE', 'ru', 'Проверка просрочена'),
('quality.issue.VERIFICATION_OVERDUE', 'uz', 'Tekshiruv muddati o‘tgan'),
('quality.issue.VERIFICATION_OVERDUE', 'fr', 'Vérification en retard'),
('quality.issue.SOURCE_MISSING', 'en', 'Official source missing'),
('quality.issue.SOURCE_MISSING', 'ru', 'Нет официального источника'),
('quality.issue.SOURCE_MISSING', 'uz', 'Rasmiy manba yo‘q'),
('quality.issue.SOURCE_MISSING', 'fr', 'Source officielle manquante'),
('quality.issue.INFORMATION_INCOMPLETE', 'en', 'Required information incomplete'),
('quality.issue.INFORMATION_INCOMPLETE', 'ru', 'Не заполнены обязательные сведения'),
('quality.issue.INFORMATION_INCOMPLETE', 'uz', 'Majburiy ma’lumotlar to‘liq emas'),
('quality.issue.INFORMATION_INCOMPLETE', 'fr', 'Informations obligatoires incomplètes'),
('quality.issue.TRANSLATIONS_MISSING', 'en', 'Translations missing'),
('quality.issue.TRANSLATIONS_MISSING', 'ru', 'Нет переводов'),
('quality.issue.TRANSLATIONS_MISSING', 'uz', 'Tarjimalar yo‘q'),
('quality.issue.TRANSLATIONS_MISSING', 'fr', 'Traductions manquantes'),
('quality.hint.VERIFICATION_OVERDUE', 'en', 'Published cards not checked within 180 days'),
('quality.hint.VERIFICATION_OVERDUE', 'ru', 'Опубликованные карточки без проверки за 180 дней'),
('quality.hint.VERIFICATION_OVERDUE', 'uz', '180 kun ichida tekshirilmagan e’lon qilingan kartalar'),
('quality.hint.VERIFICATION_OVERDUE', 'fr', 'Fiches publiées non vérifiées depuis 180 jours'),
('quality.hint.SOURCE_MISSING', 'en', 'No usable link to the official source'),
('quality.hint.SOURCE_MISSING', 'ru', 'Нет рабочей ссылки на официальный источник'),
('quality.hint.SOURCE_MISSING', 'uz', 'Rasmiy manbaga yaroqli havola yo‘q'),
('quality.hint.SOURCE_MISSING', 'fr', 'Aucun lien exploitable vers la source officielle'),
('quality.hint.INFORMATION_INCOMPLETE', 'en', 'Fields the editor marks as required are empty'),
('quality.hint.INFORMATION_INCOMPLETE', 'ru', 'Пусты поля, обязательные в редакторе'),
('quality.hint.INFORMATION_INCOMPLETE', 'uz', 'Muharrirdagi majburiy maydonlar bo‘sh'),
('quality.hint.INFORMATION_INCOMPLETE', 'fr', 'Des champs obligatoires de l’éditeur sont vides'),
('quality.hint.TRANSLATIONS_MISSING', 'en', 'Not translated into every active language'),
('quality.hint.TRANSLATIONS_MISSING', 'ru', 'Переведены не на все активные языки'),
('quality.hint.TRANSLATIONS_MISSING', 'uz', 'Barcha faol tillarga tarjima qilinmagan'),
('quality.hint.TRANSLATIONS_MISSING', 'fr', 'Pas traduites dans toutes les langues actives'),
('quality.reason.NEVER_VERIFIED', 'en', 'Published but never checked against the official source. Check it and mark it as verified.'),
('quality.reason.NEVER_VERIFIED', 'ru', 'Опубликована, но ни разу не сверена с официальным источником. Проверьте её и отметьте как проверенную.'),
('quality.reason.NEVER_VERIFIED', 'uz', 'E’lon qilingan, lekin rasmiy manba bilan hech tekshirilmagan. Tekshirib, tekshirilgan deb belgilang.'),
('quality.reason.NEVER_VERIFIED', 'fr', 'Publiée mais jamais comparée à la source officielle. Vérifiez-la et marquez-la comme vérifiée.'),
('quality.reason.RECHECK_DUE', 'en', 'The last check is more than 180 days old. Check the card against the official source again.'),
('quality.reason.RECHECK_DUE', 'ru', 'Последней проверке больше 180 дней. Снова сверьте карточку с официальным источником.'),
('quality.reason.RECHECK_DUE', 'uz', 'Oxirgi tekshiruvdan 180 kundan ko‘p vaqt o‘tgan. Kartani rasmiy manba bilan qayta tekshiring.'),
('quality.reason.RECHECK_DUE', 'fr', 'La dernière vérification date de plus de 180 jours. Comparez de nouveau la fiche à la source officielle.'),
('quality.reason.CHANGED_SINCE_VERIFICATION', 'en', 'The card changed after its last check. Check it against the official source again.'),
('quality.reason.CHANGED_SINCE_VERIFICATION', 'ru', 'Карточка изменилась после последней проверки. Снова сверьте её с официальным источником.'),
('quality.reason.CHANGED_SINCE_VERIFICATION', 'uz', 'Karta oxirgi tekshiruvdan keyin o‘zgargan. Uni rasmiy manba bilan qayta tekshiring.'),
('quality.reason.CHANGED_SINCE_VERIFICATION', 'fr', 'La fiche a changé depuis la dernière vérification. Comparez-la de nouveau à la source officielle.'),
('quality.reason.MISSING', 'en', 'Add a link to the official source page (a full https:// address).'),
('quality.reason.MISSING', 'ru', 'Добавьте ссылку на страницу официального источника (полный адрес https://).'),
('quality.reason.MISSING', 'uz', 'Rasmiy manba sahifasiga havola qo‘shing (to‘liq https:// manzil).'),
('quality.reason.MISSING', 'fr', 'Ajoutez un lien vers la page de la source officielle (adresse complète en https://).'),
('quality.reason.UNUSABLE', 'en', 'The official source link is not a valid web address. Replace it with a full https:// link.'),
('quality.reason.UNUSABLE', 'ru', 'Ссылка на официальный источник не является веб-адресом. Замените её полной ссылкой https://.'),
('quality.reason.UNUSABLE', 'uz', 'Rasmiy manba havolasi yaroqli veb-manzil emas. Uni to‘liq https:// havola bilan almashtiring.'),
('quality.reason.UNUSABLE', 'fr', 'Le lien vers la source officielle n’est pas une adresse web valide. Remplacez-le par un lien complet en https://.'),
('quality.reason.REQUIRED_FIELDS', 'en', 'Fill in the required fields:'),
('quality.reason.REQUIRED_FIELDS', 'ru', 'Заполните обязательные поля:'),
('quality.reason.REQUIRED_FIELDS', 'uz', 'Majburiy maydonlarni to‘ldiring:'),
('quality.reason.REQUIRED_FIELDS', 'fr', 'Remplissez les champs obligatoires :'),
('quality.reason.LANGUAGES', 'en', 'Add translations for:'),
('quality.reason.LANGUAGES', 'ru', 'Добавьте переводы на:'),
('quality.reason.LANGUAGES', 'uz', 'Quyidagi tillarga tarjima qo‘shing:'),
('quality.reason.LANGUAGES', 'fr', 'Ajoutez les traductions pour :'),
('reminders.title', 'en', 'Reminders'),
('reminders.title', 'ru', 'Напоминания'),
('reminders.title', 'uz', 'Eslatmalar'),
('reminders.title', 'fr', 'Rappels'),
('reminders.subtitle', 'en', 'Created by a daily check. An acknowledged reminder returns after 14 days if the issue is still open.'),
('reminders.subtitle', 'ru', 'Создаются ежедневной проверкой. Принятое к сведению напоминание вернётся через 14 дней, если проблема не решена.'),
('reminders.subtitle', 'uz', 'Kundalik tekshiruv tomonidan yaratiladi. Qabul qilingan eslatma muammo hal qilinmasa, 14 kundan keyin qaytadi.'),
('reminders.subtitle', 'fr', 'Créés par une vérification quotidienne. Un rappel marqué comme vu revient après 14 jours si le problème persiste.'),
('reminders.detected', 'en', 'Detected:'),
('reminders.detected', 'ru', 'Обнаружено:'),
('reminders.detected', 'uz', 'Aniqlangan:'),
('reminders.detected', 'fr', 'Détecté le'),
('reminders.acknowledge', 'en', 'Acknowledge'),
('reminders.acknowledge', 'ru', 'Принять к сведению'),
('reminders.acknowledge', 'uz', 'Qabul qilish'),
('reminders.acknowledge', 'fr', 'Marquer comme vu'),
('reminders.acknowledged', 'en', 'Reminder hidden for 14 days'),
('reminders.acknowledged', 'ru', 'Напоминание скрыто на 14 дней'),
('reminders.acknowledged', 'uz', 'Eslatma 14 kunga yashirildi'),
('reminders.acknowledged', 'fr', 'Rappel masqué pendant 14 jours'),
('reminders.dashboardHint', 'en', 'Quality issues to follow up'),
('reminders.dashboardHint', 'ru', 'Проблемы качества для отработки'),
('reminders.dashboardHint', 'uz', 'Hal qilinishi kerak bo‘lgan sifat muammolari'),
('reminders.dashboardHint', 'fr', 'Problèmes de qualité à suivre'),
('reports.status.IN_PROGRESS', 'en', 'In progress'),
('reports.status.IN_PROGRESS', 'ru', 'В работе'),
('reports.status.IN_PROGRESS', 'uz', 'Ko‘rib chiqilmoqda'),
('reports.status.IN_PROGRESS', 'fr', 'En cours'),
('reports.status.REJECTED', 'en', 'Rejected'),
('reports.status.REJECTED', 'ru', 'Отклонено'),
('reports.status.REJECTED', 'uz', 'Rad etildi'),
('reports.status.REJECTED', 'fr', 'Rejeté'),
('reports.startHandling', 'en', 'Start handling'),
('reports.startHandling', 'ru', 'Взять в работу'),
('reports.startHandling', 'uz', 'Ko‘rib chiqishni boshlash'),
('reports.startHandling', 'fr', 'Prendre en charge'),
('reports.reject', 'en', 'Reject'),
('reports.reject', 'ru', 'Отклонить'),
('reports.reject', 'uz', 'Rad etish'),
('reports.reject', 'fr', 'Rejeter'),
('reports.reopen', 'en', 'Reopen'),
('reports.reopen', 'ru', 'Открыть снова'),
('reports.reopen', 'uz', 'Qayta ochish'),
('reports.reopen', 'fr', 'Rouvrir'),
('reports.explanation', 'en', 'Explanation'),
('reports.explanation', 'ru', 'Пояснение'),
('reports.explanation', 'uz', 'Izoh'),
('reports.explanation', 'fr', 'Explication'),
('reports.explanationHint', 'en', 'Required when rejecting a report. Visible to staff only and kept in the history.'),
('reports.explanationHint', 'ru', 'Обязательно при отклонении сообщения. Видно только сотрудникам и сохраняется в истории.'),
('reports.explanationHint', 'uz', 'Xabarni rad etishda majburiy. Faqat xodimlarga ko‘rinadi va tarixda saqlanadi.'),
('reports.explanationHint', 'fr', 'Obligatoire pour rejeter un signalement. Visible uniquement par le personnel et conservée dans l’historique.'),
('reports.rejectNeedsNote', 'en', 'Explain why the report is rejected.'),
('reports.rejectNeedsNote', 'ru', 'Объясните, почему сообщение отклоняется.'),
('reports.rejectNeedsNote', 'uz', 'Xabar nima uchun rad etilayotganini tushuntiring.'),
('reports.rejectNeedsNote', 'fr', 'Expliquez pourquoi le signalement est rejeté.'),
('reports.latestNote', 'en', 'Latest explanation'),
('reports.latestNote', 'ru', 'Последнее пояснение'),
('reports.latestNote', 'uz', 'Oxirgi izoh'),
('reports.latestNote', 'fr', 'Dernière explication'),
('reports.history', 'en', 'History'),
('reports.history', 'ru', 'История'),
('reports.history', 'uz', 'Tarix'),
('reports.history', 'fr', 'Historique'),
('reports.history.received', 'en', 'Report received'),
('reports.history.received', 'ru', 'Сообщение получено'),
('reports.history.received', 'uz', 'Xabar qabul qilindi'),
('reports.history.received', 'fr', 'Signalement reçu'),
('reports.history.changed', 'en', 'Status changed'),
('reports.history.changed', 'ru', 'Статус изменён'),
('reports.history.changed', 'uz', 'Holat o‘zgartirildi'),
('reports.history.changed', 'fr', 'Statut modifié'),
('reports.history.visitor', 'en', 'Visitor'),
('reports.history.visitor', 'ru', 'Посетитель'),
('reports.history.visitor', 'uz', 'Tashrifchi'),
('reports.history.visitor', 'fr', 'Visiteur'),
('reports.contactHidden', 'en', 'The visitor left contact details. Only staff who handle reports can see them.'),
('reports.contactHidden', 'ru', 'Посетитель оставил контакты. Их видят только сотрудники, которые обрабатывают сообщения.'),
('reports.contactHidden', 'uz', 'Tashrifchi aloqa ma’lumotlarini qoldirgan. Ularni faqat xabarlarni ko‘rib chiquvchi xodimlar ko‘ra oladi.'),
('reports.contactHidden', 'fr', 'Le visiteur a laissé ses coordonnées. Seul le personnel qui traite les signalements peut les voir.'),
('reports.cardChanged', 'en', 'The service card was edited after this report arrived. Check whether the edit fixed the problem before you resolve the report.'),
('reports.cardChanged', 'ru', 'Карточка услуги изменялась после получения сообщения. Прежде чем закрыть сообщение, проверьте, устранило ли изменение проблему.'),
('reports.cardChanged', 'uz', 'Xabar kelganidan keyin xizmat kartasi tahrir qilingan. Xabarni yopishdan oldin tahrir muammoni hal qilganini tekshiring.'),
('reports.cardChanged', 'fr', 'La fiche du service a été modifiée après la réception de ce signalement. Vérifiez si la modification a corrigé le problème avant de le résoudre.'),
('reports.service', 'en', 'Service'),
('reports.service', 'ru', 'Услуга'),
('reports.service', 'uz', 'Xizmat'),
('reports.service', 'fr', 'Service'),
('reports.allServices', 'en', 'All services'),
('reports.allServices', 'ru', 'Все услуги'),
('reports.allServices', 'uz', 'Barcha xizmatlar'),
('reports.allServices', 'fr', 'Tous les services'),
('reports.allProblems', 'en', 'All problem types'),
('reports.allProblems', 'ru', 'Все типы проблем'),
('reports.allProblems', 'uz', 'Barcha muammo turlari'),
('reports.allProblems', 'fr', 'Tous les types de problème'),
('reports.dashboardSection', 'en', 'Visitor reports'),
('reports.dashboardSection', 'ru', 'Сообщения посетителей'),
('reports.dashboardSection', 'uz', 'Tashrifchilar xabarlari'),
('reports.dashboardSection', 'fr', 'Signalements des visiteurs'),
('reports.dashboardSectionHint', 'en', 'Unresolved counts are current; received counts follow the selected period.'),
('reports.dashboardSectionHint', 'ru', 'Нерешённые — на текущий момент; полученные — за выбранный период.'),
('reports.dashboardSectionHint', 'uz', 'Hal qilinmaganlar joriy holat bo‘yicha, kelib tushganlar tanlangan davr bo‘yicha.'),
('reports.dashboardSectionHint', 'fr', 'Les non résolus sont comptés à ce jour ; les reçus suivent la période choisie.'),
('reports.exportPeriod', 'en', 'Period CSV'),
('reports.exportPeriod', 'ru', 'CSV за период'),
('reports.exportPeriod', 'uz', 'Davr CSV'),
('reports.exportPeriod', 'fr', 'CSV de la période'),
('reports.unresolved', 'en', 'Unresolved'),
('reports.unresolved', 'ru', 'Не решены'),
('reports.unresolved', 'uz', 'Hal qilinmagan'),
('reports.unresolved', 'fr', 'Non résolus'),
('reports.unresolvedHint', 'en', 'New or in progress right now'),
('reports.unresolvedHint', 'ru', 'Новые или в работе сейчас'),
('reports.unresolvedHint', 'uz', 'Hozir yangi yoki ko‘rib chiqilmoqda'),
('reports.unresolvedHint', 'fr', 'Nouveaux ou en cours actuellement'),
('reports.newHint', 'en', 'Not picked up yet'),
('reports.newHint', 'ru', 'Ещё не взяты в работу'),
('reports.newHint', 'uz', 'Hali ko‘rib chiqilmagan'),
('reports.newHint', 'fr', 'Pas encore pris en charge'),
('reports.inProgressHint', 'en', 'Being handled by staff'),
('reports.inProgressHint', 'ru', 'Обрабатываются сотрудниками'),
('reports.inProgressHint', 'uz', 'Xodimlar ko‘rib chiqmoqda'),
('reports.inProgressHint', 'fr', 'En cours de traitement'),
('reports.receivedInPeriod', 'en', 'Received in period'),
('reports.receivedInPeriod', 'ru', 'Получено за период'),
('reports.receivedInPeriod', 'uz', 'Davr ichida kelib tushgan'),
('reports.receivedInPeriod', 'fr', 'Reçus sur la période'),
('reports.openList', 'en', 'Open reports'),
('reports.openList', 'ru', 'Открытые сообщения'),
('reports.openList', 'uz', 'Ochiq xabarlar'),
('reports.openList', 'fr', 'Signalements ouverts'),
('reports.noOpenTitle', 'en', 'No open reports'),
('reports.noOpenTitle', 'ru', 'Открытых сообщений нет'),
('reports.noOpenTitle', 'uz', 'Ochiq xabarlar yo‘q'),
('reports.noOpenTitle', 'fr', 'Aucun signalement ouvert'),
('reports.noOpenText', 'en', 'Reports that need handling will appear here.'),
('reports.noOpenText', 'ru', 'Здесь появятся сообщения, требующие обработки.'),
('reports.noOpenText', 'uz', 'Ko‘rib chiqilishi kerak bo‘lgan xabarlar shu yerda chiqadi.'),
('reports.noOpenText', 'fr', 'Les signalements à traiter apparaîtront ici.');
INSERT INTO translation_keys (translation_key, required, active)
SELECT DISTINCT key, TRUE, TRUE FROM organization_analytics_labels ON CONFLICT (translation_key) DO NOTHING;
INSERT INTO translations (translation_key_id, language_code, translation_value)
SELECT k.id, s.lang, s.value FROM organization_analytics_labels s JOIN translation_keys k ON k.translation_key = s.key
ON CONFLICT (language_code, translation_key_id) DO NOTHING;
UPDATE translation_keys SET active = FALSE
WHERE translation_key IN ('reports.status.IN_REVIEW', 'reports.status.DISMISSED', 'reports.dismiss', 'reports.startReview', 'reports.markNew', 'reports.filteredByEntity', 'reports.note', 'reports.noteHint');
